import type {
  Conversation,
  Message,
  Notification,
  Post,
  PostComment,
  Profile,
  Space,
  Story,
} from "@/lib/types";
import { SEED_POSTS_BATCH_1 } from "./seed-posts-batch1";
import { SEED_POSTS_BATCH_2 } from "./seed-posts-batch2";
import { SEED_POSTS_EXTRA_200 } from "./seed-posts-extra";
import { SEED_POSTS_BATCH_3_100 } from "./seed-posts-batch3";

/* ----------------------------------------------------------------- Profiles */

export const SEED_PROFILES: Profile[] = [
  {
    id: "user_alexrivers",
    username: "alexrivers",
    display_name: "Alex Rivers",
    bio: "Design Director & Spatial Computing Researcher. Exploring the intersections of voice, tactile UI & distributed social spaces. ☕🎧",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80",
    location: "San Francisco, CA",
    website: "https://alexrivers.design",
    followers: 4820,
    following: 340,
    verified: true,
    plan: "pro",
    role: "user",
    status: "active",
    warning_count: 0,
    joined_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "user_elenarostova",
    username: "elenarostova",
    display_name: "Elena Rostova",
    bio: "Modular Synthesizer Artist & Sound Architect. Streaming ambient soundscapes, analog masterclasses & spatial audio rooms.",
    avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=256&q=80",
    location: "Berlin, Germany",
    website: "https://sound.elenarostova.io",
    followers: 8940,
    following: 195,
    verified: true,
    plan: "pro",
    role: "user",
    status: "active",
    warning_count: 0,
    joined_at: "2024-02-10T00:00:00Z",
  },
  {
    id: "user_marcuschen",
    username: "marcuschen",
    display_name: "Marcus Chen",
    bio: "Distributed systems engineer & audio latency obsessive. Building real-time protocols for live interactive experiences. ⚡",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80",
    location: "Tokyo, Japan",
    website: "https://chen.systems",
    followers: 6120,
    following: 280,
    verified: true,
    plan: "pro",
    role: "user",
    status: "active",
    warning_count: 0,
    joined_at: "2024-03-01T00:00:00Z",
  },
  {
    id: "user_sophiaz",
    username: "sophiaz",
    display_name: "Sophia Zhang",
    bio: "Lead Design Systems Architect. Curating typography, OKLCH color spaces, and micro-interactions for modern web applications.",
    avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=256&q=80",
    location: "New York, NY",
    website: "https://sophiazhang.co",
    followers: 12400,
    following: 412,
    verified: true,
    plan: "pro",
    role: "user",
    status: "active",
    warning_count: 0,
    joined_at: "2023-11-20T00:00:00Z",
  },
  {
    id: "user_davidk",
    username: "davidk",
    display_name: "David Kim",
    bio: "Visual Storyteller & Cinematographer. Capturing high-contrast street moments and architectural geometries around the globe. 📷",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80",
    location: "Seoul, South Korea",
    website: "https://davidkim.camera",
    followers: 7300,
    following: 310,
    verified: true,
    plan: "pro",
    role: "user",
    status: "active",
    warning_count: 0,
    joined_at: "2024-04-05T00:00:00Z",
  },
  {
    id: "user_maya_patel",
    username: "mayapatel",
    display_name: "Maya Patel",
    bio: "AI Research Scientist & Creative Technologist. Exploring multi-modal models, synthetic voice interfaces & autonomous software agents. 🤖✨",
    avatar_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&q=80",
    location: "London, UK",
    website: "https://mayapatel.ai",
    followers: 15200,
    following: 390,
    verified: true,
    plan: "pro",
    role: "user",
    status: "active",
    warning_count: 0,
    joined_at: "2023-09-12T00:00:00Z",
  },
  {
    id: "user_liam_o_connor",
    username: "liamoc",
    display_name: "Liam O'Connor",
    bio: "Indie Founder & Bootstrapper. Building profitable micro-SaaS businesses in public. Sharing metrics, MRR updates & growth playbooks. 📈",
    avatar_url: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=256&q=80",
    location: "Dublin, Ireland",
    website: "https://liam.build",
    followers: 9800,
    following: 512,
    verified: true,
    plan: "plus",
    role: "user",
    status: "active",
    warning_count: 0,
    joined_at: "2024-01-08T00:00:00Z",
  },
  {
    id: "user_amara_okafor",
    username: "amaraokafor",
    display_name: "Amara Okafor",
    bio: "Product Strategist & FinTech Pioneer. Passionate about cross-border African commerce, Paystack creator monetization & mobile banking rails. 🌍💳",
    avatar_url: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=256&q=80",
    location: "Lagos, Nigeria",
    website: "https://amara.africa",
    followers: 11300,
    following: 240,
    verified: true,
    plan: "pro",
    role: "user",
    status: "active",
    warning_count: 0,
    joined_at: "2023-12-01T00:00:00Z",
  },
  {
    id: "user_kenji_sato",
    username: "kenjisato",
    display_name: "Kenji Sato",
    bio: "Creative Developer & WebGL Shader Wizard. Crafting real-time generative audio visualizers & fluid simulations. 🎨💻",
    avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=256&q=80",
    location: "Kyoto, Japan",
    website: "https://kenji.gl",
    followers: 6700,
    following: 180,
    verified: true,
    plan: "plus",
    role: "user",
    status: "active",
    warning_count: 0,
    joined_at: "2024-02-18T00:00:00Z",
  },
  {
    id: "user_clara_valdez",
    username: "claravaldez",
    display_name: "Clara Valdez",
    bio: "Editorial Photographer & Visual Chronicler. Documenting brutalist architecture, minimal interiors & urban landscapes. 🏛️",
    avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80",
    location: "Barcelona, Spain",
    website: "https://claravaldez.photo",
    followers: 8400,
    following: 295,
    verified: true,
    plan: "plus",
    role: "user",
    status: "active",
    warning_count: 0,
    joined_at: "2024-03-15T00:00:00Z",
  },
  {
    id: "user_devon_miles",
    username: "devonmiles",
    display_name: "Devon Miles",
    bio: "Sound Engineer & Podcast Producer. Building the future of spatial voice discussions and low-noise acoustic rooms. 🎙️",
    avatar_url: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=256&q=80",
    location: "Austin, TX",
    website: "https://devonmiles.audio",
    followers: 5300,
    following: 210,
    verified: false,
    plan: "plus",
    role: "user",
    status: "active",
    warning_count: 0,
    joined_at: "2024-04-10T00:00:00Z",
  },
  {
    id: "user_zara_alvarez",
    username: "zaraalvarez",
    display_name: "Zara Alvarez",
    bio: "UX Researcher & Accessibility Advocate. Obsessed with high contrast typography, screen reader ergonomics and neurodiverse UI. ♿✨",
    avatar_url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=256&q=80",
    location: "Toronto, Canada",
    website: "https://zaraa11y.design",
    followers: 9100,
    following: 430,
    verified: true,
    plan: "pro",
    role: "user",
    status: "active",
    warning_count: 0,
    joined_at: "2023-11-05T00:00:00Z",
  },
  {
    id: "user_spacesnext",
    username: "spacesnext",
    display_name: "Spaces Next",
    bio: "Official Community & Product Updates account for Spaces. Connecting creators worldwide through live audio, rich stories & direct tips. ✨",
    avatar_url: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=256&q=80",
    location: "Global",
    website: "https://spaces.social",
    followers: 24500,
    following: 12,
    verified: true,
    plan: "pro",
    role: "user",
    status: "active",
    warning_count: 0,
    joined_at: "2023-10-01T00:00:00Z",
  },
  {
    id: "user_kai_turing",
    username: "kaitech",
    display_name: "Kai Turing",
    bio: "Senior Staff Engineer & Distributed Sarcasm Specialist. Deploying to prod on Friday so the weekend has purpose. ☕🔥",
    avatar_url: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=256&q=80",
    location: "Seattle, WA",
    website: "https://kai.codes",
    followers: 18400,
    following: 340,
    verified: true,
    plan: "pro",
    role: "user",
    status: "active",
    warning_count: 0,
    joined_at: "2023-08-15T00:00:00Z",
  },
  {
    id: "user_priya_sharma",
    username: "priyacoffee",
    display_name: "Priya Sharma",
    bio: "Q-Grader Specialty Coffee Roaster & Chemex Alchemist. Documenting micro-lot beans, extraction science & sourdough. ☕🌾",
    avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80",
    location: "Melbourne, Australia",
    website: "https://priya.coffee",
    followers: 14200,
    following: 280,
    verified: true,
    plan: "pro",
    role: "user",
    status: "active",
    warning_count: 0,
    joined_at: "2023-09-01T00:00:00Z",
  },
  {
    id: "user_samir_k",
    username: "samirgaming",
    display_name: "Samir K.",
    bio: "Indie Game Designer & Cyberpunk Pixel Artist. Crafting retro synthwave RPGs with compute shaders & custom chiptunes. 🎮👾",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80",
    location: "Montreal, Canada",
    website: "https://samir.games",
    followers: 12900,
    following: 215,
    verified: true,
    plan: "plus",
    role: "user",
    status: "active",
    warning_count: 0,
    joined_at: "2024-01-20T00:00:00Z",
  },
  {
    id: "user_chloe_dubois",
    username: "chloefit",
    display_name: "Chloé Dubois",
    bio: "Sports Biomechanist & Ultra-Endurance Athlete. Fueling clean miles, Zone 2 physiology & alpine trail aesthetics. 🏃‍♀️🏔️",
    avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=256&q=80",
    location: "Chamonix, France",
    website: "https://chloedubois.run",
    followers: 16700,
    following: 390,
    verified: true,
    plan: "pro",
    role: "user",
    status: "active",
    warning_count: 0,
    joined_at: "2023-07-10T00:00:00Z",
  },
  {
    id: "user_dr_tariq_amin",
    username: "tariqastro",
    display_name: "Dr. Tariq Amin",
    bio: "Astrophysicist & Deep Field Stargazer. Exploring gravitational lenses, James Webb spectra & cosmic philosophy. 🔭🌌",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80",
    location: "Oxford, UK",
    website: "https://tariqamin.space",
    followers: 21300,
    following: 150,
    verified: true,
    plan: "pro",
    role: "user",
    status: "active",
    warning_count: 0,
    joined_at: "2023-05-18T00:00:00Z",
  },
  {
    id: "user_hannah_brooks",
    username: "hannahcomedy",
    display_name: "Hannah Brooks",
    bio: "Tech Humorist & Ex-Consultant. Translating corporate synergy buzzwords into understandable absurdity. 🎤🎭",
    avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=256&q=80",
    location: "Chicago, IL",
    website: "https://hannahbrooks.live",
    followers: 28900,
    following: 512,
    verified: true,
    plan: "pro",
    role: "user",
    status: "active",
    warning_count: 0,
    joined_at: "2023-06-25T00:00:00Z",
  },
];

/* ----------------------------------------------------------------- Seed Posts (300+ Posts) */

// Base social posts
const BASE_RAW_POST_TEMPLATES: {
  userId: string;
  content: string;
  media?: string | null;
  tags: string[];
  poll?: any;
  likes: number;
  comments: number;
  reposts: number;
  views: number;
  hoursAgo: number;
}[] = [
  {
    userId: "user_elenarostova",
    content: "Just wrapped up a 3-hour generative ambient session in the studio using Eurorack modules and tape loops. Spatial acoustics make all the difference in audio rooms. Drop your favorite headphones below! 🎧✨",
    media: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=80",
    tags: ["sounddesign", "ambient", "creators", "musicproduction"],
    likes: 142,
    comments: 19,
    reposts: 28,
    views: 1840,
    hoursAgo: 1,
  },
  {
    userId: "user_alexrivers",
    content: "Interactive Community Poll: When tuning into live audio spaces, which feature provides the most value for your listening experience?",
    tags: ["spaces", "product", "community", "audio"],
    poll: {
      id: "poll_seed_1",
      question: "Which live room capability matters most to you?",
      options: [
        { id: "opt_1", text: "Low-latency HD audio streams", votes: 412 },
        { id: "opt_2", text: "Direct live creator tipping", votes: 289 },
        { id: "opt_3", text: "Instant AI transcriptions & recaps", votes: 531 },
        { id: "opt_4", text: "Collaborative interactive stage chat", votes: 194 },
      ],
      totalVotes: 1426,
    },
    likes: 98,
    comments: 34,
    reposts: 14,
    views: 2150,
    hoursAgo: 2,
  },
  {
    userId: "user_sophiaz",
    content: "A quick reminder for all UI builders: accessible contrast ratios are not optional. Here is our new OKLCH dark mode palette pairing soft warm grays with 14.5:1 text legibility. Minimal eye strain, maximum elegance. 🎨✨",
    media: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80",
    tags: ["designsystems", "typography", "accessibility", "uiux"],
    likes: 245,
    comments: 26,
    reposts: 64,
    views: 4120,
    hoursAgo: 3,
  },
  {
    userId: "user_maya_patel",
    content: "We just open-sourced our multi-agent audio routing benchmark. Running real-time speech diarization and sentiment summarization on device with sub-50ms overhead. The future of live conversation interfaces is astonishing. 🚀🤖",
    media: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
    tags: ["artificialintelligence", "machinelearning", "research", "opensource"],
    likes: 389,
    comments: 41,
    reposts: 88,
    views: 6400,
    hoursAgo: 4,
  },
  {
    userId: "user_amara_okafor",
    content: "Creator Monetization is now live! Creators can receive instant tips, activate monthly subscriber perks, and initiate direct Paystack withdrawals into bank accounts and mobile wallets. 🚀💸",
    media: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1200&q=80",
    tags: ["monetization", "paystack", "fintech", "africa"],
    likes: 512,
    comments: 72,
    reposts: 140,
    views: 9200,
    hoursAgo: 5,
  },
  {
    userId: "user_marcuschen",
    content: "Benchmarking WebRTC audio transports under 20% simulated packet loss. Using Opus CELT encoding with adaptive jitter buffers cut dropouts by 84%. Live spaces feel crisp even on shaky 3G mobile connections. ⚡📻",
    tags: ["webrtc", "networking", "distributedsystems", "performance"],
    likes: 184,
    comments: 22,
    reposts: 39,
    views: 3100,
    hoursAgo: 6,
  },
  {
    userId: "user_davidk",
    content: "Dusk over Shibuya crossing captured at 50mm f/1.2 on Ilford Delta 400. High-contrast monochrome captures human momentum in a way digital sensors can rarely replicate. 📷🌃",
    media: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
    tags: ["photography", "tokyo", "streetphotography", "monochrome"],
    likes: 670,
    comments: 48,
    reposts: 95,
    views: 8900,
    hoursAgo: 7,
  },
  {
    userId: "user_liam_o_connor",
    content: "Month 4 milestone: crossed $18,400 MRR on our developer analytics tool with zero VC funding and a 2-person team. The single highest leverage change? Adding instant Paystack checkout for emerging market subscribers. 📈🎉",
    tags: ["indiehackers", "buildinpublic", "saas", "bootstrapping"],
    likes: 420,
    comments: 53,
    reposts: 81,
    views: 7300,
    hoursAgo: 8,
  },
  {
    userId: "user_kenji_sato",
    content: "Experiments in reactive WebGL particles driven by microphone frequency inputs. Each speaker's pitch changes the fractal geometry and color dispersal in real time. Code snippet in the thread! 🎨💻",
    media: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80",
    tags: ["webgl", "creativecoding", "threejs", "shaders"],
    likes: 310,
    comments: 29,
    reposts: 72,
    views: 5200,
    hoursAgo: 9,
  },
  {
    userId: "user_zara_alvarez",
    content: "Friendly reminder to test your web apps with screen readers enabled and keyboard navigation only (Tab, Shift+Tab, Enter, Escape). If users cannot navigate your modals without a mouse, your UI is incomplete. ♿💡",
    tags: ["a11y", "accessibility", "webdev", "frontend"],
    likes: 380,
    comments: 31,
    reposts: 110,
    views: 5800,
    hoursAgo: 10,
  },
  {
    userId: "user_clara_valdez",
    content: "Brutalist concrete reflections after rain in Valencia. The way natural light carves negative space between raw pillars is endlessly inspiring for physical and digital layouts alike. 🏛️",
    media: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
    tags: ["architecture", "minimalism", "design", "photography"],
    likes: 290,
    comments: 18,
    reposts: 42,
    views: 3900,
    hoursAgo: 11,
  },
  {
    userId: "user_devon_miles",
    content: "Testing dynamic broadcast microphone capsules: Shure SM7B vs Electro-Voice RE20 for live podcasting rooms. Which one do you prefer for rich vocal presence without room echo?",
    poll: {
      id: "poll_seed_2",
      question: "Best vocal mic for live audio rooms?",
      options: [
        { id: "mic_1", text: "Shure SM7B (Warm & intimate)", votes: 624 },
        { id: "mic_2", text: "Electro-Voice RE20 (Crisp & broadcast)", votes: 381 },
        { id: "mic_3", text: "Rode PodMic / USB mic", votes: 245 },
        { id: "mic_4", text: "AirPods / Built-in mic", votes: 112 },
      ],
      totalVotes: 1362,
    },
    tags: ["audio", "podcasting", "microphones", "gear"],
    likes: 195,
    comments: 44,
    reposts: 26,
    views: 3400,
    hoursAgo: 12,
  },
  {
    userId: "user_spacesnext",
    content: "Introducing Creator Monetization Hub on Spaces! Receive direct fan tips, set up verified Paystack bank/mobile money payouts, and monetize your live audio broadcasts with zero stress. 🚀✨",
    media: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80",
    tags: ["productupdate", "monetization", "creators", "spaces"],
    likes: 890,
    comments: 104,
    reposts: 210,
    views: 14500,
    hoursAgo: 13,
  },
  {
    userId: "user_alexrivers",
    content: "Why spatial audio matters for digital social clubs: when everyone's voice emanates from a distinct acoustic coordinate, conversation flow becomes conversational, interruptions drop by 60%, and listener fatigue vanishes. 🎧🧠",
    tags: ["spatialaudio", "ux", "psychology", "socialaudio"],
    likes: 275,
    comments: 32,
    reposts: 58,
    views: 4600,
    hoursAgo: 14,
  },
  {
    userId: "user_elenarostova",
    content: "Late night patch session: mixing frequency modulation with polyrhythmic step sequencers. Sometimes the happiest accidents come from plugging audio rate outputs directly into filter cutoffs. 🎹🎛️",
    media: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80",
    tags: ["modularsynth", "electronicmusic", "sounddesign", "studio"],
    likes: 315,
    comments: 27,
    reposts: 49,
    views: 4200,
    hoursAgo: 15,
  },
  {
    userId: "user_maya_patel",
    content: "Prompt engineering isn't dead—it's just moving into structured tool calling, deterministic state machines, and hierarchical agent graphs. The prompt is merely the interface contract. 🤖",
    tags: ["ai", "promptengineering", "softwarearchitecture", "agents"],
    likes: 640,
    comments: 58,
    reposts: 132,
    views: 8900,
    hoursAgo: 16,
  },
  {
    userId: "user_sophiaz",
    content: "Design tip: Never use pure black (#000000) for text or dark backgrounds in high-density apps. A deep zinc or slate (#09090b / #0f172a) softens contrast harshness while retaining visual punch. 🖋️🖤",
    tags: ["design", "colors", "frontend", "css"],
    likes: 410,
    comments: 37,
    reposts: 78,
    views: 6100,
    hoursAgo: 17,
  },
  {
    userId: "user_marcuschen",
    content: "Deploying Edge nodes in Nairobi, São Paulo, and Frankfurt reduced round-trip voice ping from 240ms down to 42ms for global listeners. Proximity to the user remains the ultimate performance optimization. 🌐🚀",
    tags: ["edgecomputing", "cloud", "networking", "latency"],
    likes: 295,
    comments: 24,
    reposts: 61,
    views: 4700,
    hoursAgo: 18,
  },
  {
    userId: "user_amara_okafor",
    content: "The creator economy in Africa is exploding. With Paystack enabling direct local currency payouts via MPESA, MTN MoMo, and regional banks, creators can finally monetize their global audiences without high remittance friction. 🌍💰",
    tags: ["africa", "fintech", "creators", "paystack"],
    likes: 540,
    comments: 63,
    reposts: 125,
    views: 8400,
    hoursAgo: 19,
  },
  {
    userId: "user_davidk",
    content: "Night market in Taipei captured under rain slicked neon reflections. The colors on the street tell a story that words could never write. 🏮🌧️",
    media: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    tags: ["streetphotography", "taipei", "cinematography", "nightphotography"],
    likes: 720,
    comments: 51,
    reposts: 114,
    views: 10400,
    hoursAgo: 20,
  },
  {
    userId: "user_liam_o_connor",
    content: "5 rules I follow when designing a pricing page that converts:\n1. Limit to 3 clear tiers\n2. Highlight the most popular choice\n3. Show annual discount savings transparently\n4. Remove all unnecessary form fields\n5. Delegate checkout to a trusted provider like Paystack. 💡📊",
    tags: ["pricing", "conversion", "cro", "saas"],
    likes: 480,
    comments: 42,
    reposts: 96,
    views: 7900,
    hoursAgo: 21,
  },
  {
    userId: "user_kenji_sato",
    content: "Procedural glass refraction shaders running in WebGL. Look at how the caustic light patterns shift as you rotate the camera angle. The web platform has evolved so much in the last 2 years. ✨🖥️",
    media: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
    tags: ["shaders", "webgl", "graphicsprogramming", "creativecoding"],
    likes: 360,
    comments: 28,
    reposts: 74,
    views: 5900,
    hoursAgo: 22,
  },
  {
    userId: "user_zara_alvarez",
    content: "Focus rings are a fundamental accessibility feature. Never set `outline: none` in CSS without providing a crisp `:focus-visible` replacement. Your keyboard and assistive tech users will thank you! 🔍⌨️",
    tags: ["accessibility", "css", "webstandards", "frontend"],
    likes: 310,
    comments: 24,
    reposts: 83,
    views: 5100,
    hoursAgo: 23,
  },
  {
    userId: "user_clara_valdez",
    content: "The geometry of sunlight through louvers in an abandoned greenhouse. Rhythm, repetition, and shadow. 🌿📐",
    media: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80",
    tags: ["minimalism", "shadows", "nature", "composition"],
    likes: 230,
    comments: 16,
    reposts: 35,
    views: 3600,
    hoursAgo: 24,
  },
  {
    userId: "user_devon_miles",
    content: "Room acoustics > expensive microphone. Putting $200 of acoustic absorption panels at primary reflection points improves your podcast clarity more than upgrading to a $1000 microphone in an untreated room. 🎙️🔇",
    tags: ["podcasting", "acoustics", "soundtreatment", "creatorgear"],
    likes: 410,
    comments: 39,
    reposts: 87,
    views: 6700,
    hoursAgo: 25,
  },
  {
    userId: "user_elenarostova",
    content: "Analog distortion has warmth because of gentle harmonic saturation. Digital clipping is harsh because of abrupt truncation. Soft-clipping diode circuits bridge the best of both worlds. 🔊⚡",
    tags: ["audioengineering", "analog", "musictech", "synth"],
    likes: 275,
    comments: 21,
    reposts: 46,
    views: 4300,
    hoursAgo: 26,
  },
  {
    userId: "user_alexrivers",
    content: "Live audio rooms are the new town square. No rehearsed edits, no algorithmic feed bias—just raw, spontaneous human dialogue. What was the most impactful voice space you ever joined? 🎙️💬",
    tags: ["community", "socialaudio", "creators", "spaces"],
    likes: 340,
    comments: 49,
    reposts: 62,
    views: 5500,
    hoursAgo: 27,
  },
  {
    userId: "user_maya_patel",
    content: "Evaluating fine-tuned models on specialized domain tasks: accuracy jumps by 40% when combined with semantic retrieval-augmented generation (RAG) rather than fine-tuning weights alone. 🧠📊",
    tags: ["rag", "ai", "datascience", "nlp"],
    likes: 490,
    comments: 38,
    reposts: 92,
    views: 7400,
    hoursAgo: 28,
  },
  {
    userId: "user_sophiaz",
    content: "Micro-interactions make good software feel alive. The tactile haptic tap when bookmarking a post or sending a tip turns digital UI into a physical sensation. ✨📱",
    tags: ["interactiondesign", "haptics", "ui", "productdesign"],
    likes: 380,
    comments: 29,
    reposts: 67,
    views: 5800,
    hoursAgo: 29,
  },
  {
    userId: "user_marcuschen",
    content: "Optimizing SQLite WAL mode with memory-mapped I/O and busy timeout handlers for embedded edge databases. Zero locks, sub-millisecond queries under 500 concurrent writes. 💾⚡",
    tags: ["databases", "sqlite", "backend", "performance"],
    likes: 310,
    comments: 25,
    reposts: 58,
    views: 4900,
    hoursAgo: 30,
  },
  {
    userId: "user_amara_okafor",
    content: "Tipping your favorite creator $5 might seem small, but when 200 people in a live room do it, you just funded an independent artist's entire month of creative freedom. Direct support changes lives. ❤️💸",
    tags: ["creatorsupport", "monetization", "community", "tipping"],
    likes: 620,
    comments: 54,
    reposts: 130,
    views: 9800,
    hoursAgo: 31,
  },
  {
    userId: "user_davidk",
    content: "Tokyo fog rolling across the bay at dawn. Silhouettes of cranes and container ships standing like gentle giants against violet skies. 🌅🚢",
    media: "https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=1200&q=80",
    tags: ["tokyo", "landscape", "dawn", "photography"],
    likes: 540,
    comments: 36,
    reposts: 88,
    views: 8200,
    hoursAgo: 32,
  },
  {
    userId: "user_liam_o_connor",
    content: "The best customer feedback often comes directly from spontaneous live chats with users. We do a weekly 'Open Stage' space where anyone can suggest features or roast our UX. The roadmap clarity is unmatched. 🗺️🎙️",
    tags: ["buildinpublic", "customerfeedback", "community", "startups"],
    likes: 320,
    comments: 28,
    reposts: 54,
    views: 5200,
    hoursAgo: 33,
  },
  {
    userId: "user_kenji_sato",
    content: "Ray marching volumetric clouds in fragment shaders. Calculating multiple scattering approximations inside a single draw call at 60 FPS on mobile GPUs. Shader toy link below! ☁️✨",
    media: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80",
    tags: ["raymarching", "shaders", "graphics", "webgl"],
    likes: 390,
    comments: 31,
    reposts: 81,
    views: 6300,
    hoursAgo: 34,
  },
  {
    userId: "user_zara_alvarez",
    content: "Motion sensitivity is real. When designing page transitions and animated lists, always honor `@media (prefers-reduced-motion: reduce)`. Your users with vestibular disorders will appreciate it. ♿💫",
    tags: ["a11y", "animation", "css", "ux"],
    likes: 340,
    comments: 22,
    reposts: 76,
    views: 5300,
    hoursAgo: 35,
  },
  {
    userId: "user_clara_valdez",
    content: "Textures of worn terracotta tiles in Seville. The patina of centuries holds an authenticity that synthetic textures can never replicate. 🧱☀️",
    media: "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=1200&q=80",
    tags: ["travel", "architecture", "textures", "spain"],
    likes: 260,
    comments: 17,
    reposts: 39,
    views: 3900,
    hoursAgo: 36,
  },
  {
    userId: "user_devon_miles",
    content: "Audio mastering checklist for live podcast distributions:\n- Target -16 LUFS integrated loudness\n- True peak max at -1.0 dBTP\n- High-pass filter roll-off below 40 Hz\n- Gentle multiband compression on vocal consonants. 🎚️🎙️",
    tags: ["audiomastering", "podcasts", "audioengineering", "broadcast"],
    likes: 375,
    comments: 33,
    reposts: 79,
    views: 6100,
    hoursAgo: 37,
  },
  {
    userId: "user_spacesnext",
    content: "Did you know you can schedule Spaces in advance, customize cover art gradients, and automatically generate AI recaps for listeners who missed the live broadcast? Explore scheduled spaces today! 🗓️✨",
    tags: ["tips", "features", "spaces", "updates"],
    likes: 490,
    comments: 42,
    reposts: 95,
    views: 7800,
    hoursAgo: 38,
  },
  {
    userId: "user_alexrivers",
    content: "Designing for tactile glass panels: subtle 1px border highlights, 12px blur radius, and 4% luminance fills create real depth without looking like amateur glassmorphism. Balance is everything. 📐💎",
    media: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1200&q=80",
    tags: ["ui", "design", "glassmorphism", "craft"],
    likes: 460,
    comments: 35,
    reposts: 98,
    views: 7200,
    hoursAgo: 39,
  },
  {
    userId: "user_elenarostova",
    content: "Tape saturation is a non-linear process that naturally compresses transients while introducing pleasing even-order harmonics. Here's a sample recording comparing digital bypass vs reel-to-reel tape. 📼🎶",
    tags: ["musicproduction", "tape", "audio", "analog"],
    likes: 310,
    comments: 26,
    reposts: 52,
    views: 4800,
    hoursAgo: 40,
  },
  {
    userId: "user_maya_patel",
    content: "The best AI tools are invisible. They don't scream 'look at this AI button'; they quietly autocomplete your thoughts, summarize messy audio transcripts, and remove cognitive friction. 🤖🧠",
    tags: ["ai", "productdesign", "ux", "futureofwork"],
    likes: 580,
    comments: 47,
    reposts: 118,
    views: 9100,
    hoursAgo: 41,
  },
  {
    userId: "user_sophiaz",
    content: "Typography hierarchy rule: When increasing font size, slightly decrease line-height and letter-spacing (tracking). Large display headlines look tight and confident, while body text stays airy and readable. 🖋️📖",
    tags: ["typography", "design", "graphicdesign", "craft"],
    likes: 520,
    comments: 38,
    reposts: 122,
    views: 8400,
    hoursAgo: 42,
  },
  {
    userId: "user_marcuschen",
    content: "Testing real-time CRDTs (Conflict-Free Replicated Data Types) for live collaborative stage whiteboards and chat reactions. Zero server-side locks and deterministic convergence. ⚡💻",
    tags: ["crdt", "realtime", "distributedsystems", "algorithms"],
    likes: 280,
    comments: 19,
    reposts: 54,
    views: 4500,
    hoursAgo: 43,
  },
  {
    userId: "user_amara_okafor",
    content: "Building for mobile-first communities means keeping bundle sizes tiny, respecting metered bandwidth, and supporting diverse local payout options. Never assume high-speed fiber or American credit cards. 📱🌍",
    tags: ["globaldev", "mobilefirst", "fintech", "inclusion"],
    likes: 670,
    comments: 58,
    reposts: 145,
    views: 10200,
    hoursAgo: 44,
  },
  {
    userId: "user_davidk",
    content: "Architectural lines of the Dongdaemun Design Plaza in Seoul at midnight. Zaha Hadid's curves feel like a spacecraft resting in the middle of a historic city. 🛸🏛️",
    media: "https://images.unsplash.com/photo-1538485399081-7191377e8241?auto=format&fit=crop&w=1200&q=80",
    tags: ["seoul", "architecture", "night", "photography"],
    likes: 610,
    comments: 43,
    reposts: 102,
    views: 9400,
    hoursAgo: 45,
  },
  {
    userId: "user_liam_o_connor",
    content: "SaaS churn drops by 35% when you implement proactive in-app notifications and creator achievement badges. People love tangible proof of progress. 🏆📊",
    tags: ["saas", "retention", "growth", "indiehackers"],
    likes: 340,
    comments: 29,
    reposts: 64,
    views: 5600,
    hoursAgo: 46,
  },
  {
    userId: "user_kenji_sato",
    content: "Audio visualizer running 100,000 GPU instanced mesh cubes vibrating with sub-bass frequencies. 60 frames per second on iPhone Safari using WebGL 2.0. 🔊✨",
    media: "https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?auto=format&fit=crop&w=1200&q=80",
    tags: ["webgl", "audioreactive", "threejs", "gpu"],
    likes: 410,
    comments: 34,
    reposts: 88,
    views: 6700,
    hoursAgo: 47,
  },
  {
    userId: "user_zara_alvarez",
    content: "Color blindness affects approximately 1 in 12 men and 1 in 200 women. Never use color alone to convey status (e.g. green for success, red for error). Always pair with an icon or clear text label! 🎨🚫",
    tags: ["accessibility", "colorblindness", "ux", "design"],
    likes: 490,
    comments: 36,
    reposts: 115,
    views: 7900,
    hoursAgo: 48,
  },
  {
    userId: "user_clara_valdez",
    content: "Quiet morning light spilling across an artist's studio in Montmartre. Brushes, raw canvas, and the smell of linseed oil. 🎨☕",
    media: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=1200&q=80",
    tags: ["art", "studio", "paris", "morninglight"],
    likes: 310,
    comments: 21,
    reposts: 48,
    views: 4900,
    hoursAgo: 49,
  },
  {
    userId: "user_devon_miles",
    content: "The psychology of ambient background music in social spaces: low tempo (60-70 BPM) binaural pads calm nervous speakers and encourage more open question-and-answer interactions. 🎶🧘",
    tags: ["audio", "psychology", "ambient", "podcasting"],
    likes: 360,
    comments: 28,
    reposts: 69,
    views: 5700,
    hoursAgo: 50,
  },
  // Posts 51 to 100: expanding rich social feed variety
  {
    userId: "user_elenarostova",
    content: "Sound design challenge: create a 30-second science fiction engine hum using only white noise, a low-pass ladder filter, and a ring modulator. Upload your results to the thread! 🛸🎛️",
    tags: ["sounddesign", "synthesizer", "audiochallenge", "creators"],
    likes: 240,
    comments: 31,
    reposts: 45,
    views: 3800,
    hoursAgo: 52,
  },
  {
    userId: "user_alexrivers",
    content: "Typography pairing of the day: Playfair Display for editorial headings paired with Plus Jakarta Sans for crisp, geometric UI body text. What's your go-to font pairing this year? 🖋️✨",
    tags: ["typography", "fonts", "design", "pairing"],
    likes: 390,
    comments: 42,
    reposts: 79,
    views: 6200,
    hoursAgo: 54,
  },
  {
    userId: "user_maya_patel",
    content: "Synthetic speech generation has reached human parity in prosody and cadence. The next frontier is real-time conversational emotional resonance—detecting hesitation, excitement, and nuance. 🎙️🤖",
    tags: ["ai", "speechsynthesis", "voiceinterfaces", "future"],
    likes: 510,
    comments: 46,
    reposts: 104,
    views: 8200,
    hoursAgo: 56,
  },
  {
    userId: "user_sophiaz",
    content: "Design Tokens are the single most powerful bridge between designers and engineers. When color, spacing, radius, and duration are tokens, redesigns take hours instead of quarters. 🌉🎨",
    tags: ["designtokens", "designsystems", "frontend", "engineering"],
    likes: 440,
    comments: 33,
    reposts: 86,
    views: 7100,
    hoursAgo: 58,
  },
  {
    userId: "user_marcuschen",
    content: "Zero-copy buffer allocation in Rust for audio stream transcoding. Reduced server CPU utilization from 45% down to 8% under 10,000 concurrent listeners. Rust in the media pipeline is unmatched. 🦀⚡",
    tags: ["rustlang", "systems", "audio", "performance"],
    likes: 590,
    comments: 52,
    reposts: 135,
    views: 9400,
    hoursAgo: 60,
  },
  {
    userId: "user_amara_okafor",
    content: "Live tipping during audio broadcasts creates immediate reciprocal energy between creators and listeners. When you hear the tip chime live, the entire room celebrates. 🎉❤️",
    tags: ["tipping", "community", "liveaudio", "monetization"],
    likes: 470,
    comments: 38,
    reposts: 91,
    views: 7600,
    hoursAgo: 62,
  },
  {
    userId: "user_davidk",
    content: "Kyoto bamboo forest after morning mist. Vertical lines stretching to infinity, filtered emerald light, and the rustle of leaves in the mountain breeze. 🎋🍃",
    media: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
    tags: ["japan", "nature", "kyoto", "photography"],
    likes: 680,
    comments: 44,
    reposts: 112,
    views: 10800,
    hoursAgo: 64,
  },
  {
    userId: "user_liam_o_connor",
    content: "If you're launching a SaaS product: don't wait for perfection. Launch the core loop, talk to your first 100 users daily, and iterate on what they actually use. Speed of feedback is your only moat. 🏃💨",
    tags: ["startups", "indiehackers", "buildinpublic", "entrepreneurship"],
    likes: 380,
    comments: 35,
    reposts: 74,
    views: 6100,
    hoursAgo: 66,
  },
  {
    userId: "user_kenji_sato",
    content: "Interactive fluid dynamics simulation on HTML5 Canvas. Drag your mouse or finger to create turbulence and iridescent color trails. Try it out on mobile! 🌊🎨",
    media: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80",
    tags: ["canvas", "javascript", "fluidsimulation", "creativecoding"],
    likes: 420,
    comments: 29,
    reposts: 83,
    views: 6900,
    hoursAgo: 68,
  },
  {
    userId: "user_zara_alvarez",
    content: "Form labels must be permanently visible. Placeholder text disappears as soon as a user starts typing, causing confusion for screen readers and users with memory constraints. Always use real `<label>` tags! 📝✅",
    tags: ["a11y", "forms", "ux", "accessibility"],
    likes: 360,
    comments: 26,
    reposts: 81,
    views: 5800,
    hoursAgo: 70,
  },
  {
    userId: "user_clara_valdez",
    content: "Golden hour over the rooftops of Lisbon. Pastel facades catching warm amber light before twilight sets in over the Tagus river. 🌆🇵🇹",
    media: "https://images.unsplash.com/photo-1509840841025-9088ba78a826?auto=format&fit=crop&w=1200&q=80",
    tags: ["lisbon", "portugal", "goldenhour", "travel"],
    likes: 530,
    comments: 37,
    reposts: 89,
    views: 8400,
    hoursAgo: 72,
  },
  {
    userId: "user_devon_miles",
    content: "Quick tip for live audio moderators: use soft audio ducking so the host's microphone automatically attenuates background music by 6 dB whenever someone speaks. Keeps voice crisp and natural! 🎚️🎙️",
    tags: ["podcasting", "audioducking", "livebroadcast", "soundtips"],
    likes: 290,
    comments: 22,
    reposts: 58,
    views: 4700,
    hoursAgo: 74,
  },
  {
    userId: "user_spacesnext",
    content: "Community Spotlight: Shoutout to all the audio hosts holding weekly spaces across design, tech, indie hacking, and music production. You make this platform vibrant every day! 🌟🎙️",
    tags: ["community", "creators", "spaces", "spotlight"],
    likes: 610,
    comments: 52,
    reposts: 120,
    views: 9900,
    hoursAgo: 76,
  },
  {
    userId: "user_alexrivers",
    content: "Spatial computing is not about strapping screens to your face; it's about breaking free of 2D bounding boxes and treating digital elements as physical acoustic and visual participants in your room. 👓🌐",
    tags: ["spatialcomputing", "xr", "futureofui", "design"],
    likes: 410,
    comments: 39,
    reposts: 84,
    views: 6600,
    hoursAgo: 78,
  },
  {
    userId: "user_elenarostova",
    content: "Analog synthesizers don't stay in tune forever, and that micro-drift is precisely what gives them character. Perfect mathematical pitch sounds sterile; organic drift feels alive. 🎛️🎵",
    tags: ["synth", "analog", "musicphilosophy", "sound"],
    likes: 380,
    comments: 31,
    reposts: 68,
    views: 5900,
    hoursAgo: 80,
  },
  {
    userId: "user_maya_patel",
    content: "Building multi-modal interfaces that understand text, audio tone, and gesture simultaneously. The barrier between computing and natural human communication is rapidly dissolving. 🤖🚀",
    tags: ["multimodal", "ai", "humancomputerinteraction", "research"],
    likes: 560,
    comments: 49,
    reposts: 114,
    views: 8800,
    hoursAgo: 82,
  },
  {
    userId: "user_sophiaz",
    content: "When designing for dark mode: never use pure white icons. Reduce opacity to 90% or use a subtle muted tone so controls don't vibrate against dark backdrops. Subtle polish wins every time. ✨🖤",
    tags: ["darkmode", "designpolish", "ui", "craft"],
    likes: 430,
    comments: 34,
    reposts: 87,
    views: 6800,
    hoursAgo: 84,
  },
  {
    userId: "user_marcuschen",
    content: "Simulating 50,000 concurrent WebSocket connections on a single c6g.4xlarge instance. Epoll event loop with kernel tuning achieved 0% connection drops. Networking at scale is art. ⚡🌐",
    tags: ["websockets", "networking", "scale", "linux"],
    likes: 490,
    comments: 41,
    reposts: 108,
    views: 7900,
    hoursAgo: 86,
  },
  {
    userId: "user_amara_okafor",
    content: "Paystack integration tip: Always listen for verified webhooks and use cryptographic signature verification. Never trust client-side callbacks alone for sensitive balance credits. Security first! 🔒💳",
    tags: ["paystack", "security", "fintech", "webhooks"],
    likes: 520,
    comments: 44,
    reposts: 118,
    views: 8300,
    hoursAgo: 88,
  },
  {
    userId: "user_davidk",
    content: "Monsoon rains pouring over glass skyscrapers in Singapore. The reflection of green gardens atop modern steel towers is the perfect synthesis of nature and metropolis. 🏙️🌧️",
    media: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1200&q=80",
    tags: ["singapore", "architecture", "rain", "photography"],
    likes: 590,
    comments: 41,
    reposts: 96,
    views: 9200,
    hoursAgo: 90,
  },
  {
    userId: "user_liam_o_connor",
    content: "Building in public isn't about bragging about wins; it's about sharing the failures, the buggy deployments, and the experiments that didn't work so others can learn without repeating the pain. 💡🤝",
    tags: ["buildinpublic", "indiehackers", "honesty", "transparency"],
    likes: 460,
    comments: 39,
    reposts: 92,
    views: 7400,
    hoursAgo: 92,
  },
  {
    userId: "user_kenji_sato",
    content: "Procedural terrain generation in WebGL using Simplex noise and fractional Brownian motion (fBm). Generating infinite mountain ranges in real time with dynamic sun shadows. 🏔️💻",
    media: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
    tags: ["procedural", "webgl", "noise", "terrain"],
    likes: 370,
    comments: 28,
    reposts: 75,
    views: 6000,
    hoursAgo: 94,
  },
  {
    userId: "user_zara_alvarez",
    content: "Ensure touch targets on mobile devices are at least 44px by 44px with adequate padding between clickable elements. Tiny buttons lead to mis-taps, frustration, and abandonment. 📱📐",
    tags: ["mobiledesign", "touchtargets", "ux", "a11y"],
    likes: 420,
    comments: 32,
    reposts: 89,
    views: 6800,
    hoursAgo: 96,
  },
  {
    userId: "user_clara_valdez",
    content: "Minimalist concrete staircase in a Copenhagen design museum. The interplay of diagonal angles and soft diffused Nordic skylight is hypnotic. 📐🏛️",
    media: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
    tags: ["copenhagen", "minimalism", "design", "architecture"],
    likes: 340,
    comments: 24,
    reposts: 54,
    views: 5200,
    hoursAgo: 98,
  },
  {
    userId: "user_devon_miles",
    content: "Podcasting recording rule #1: Always capture dual mono audio tracks for separate speakers. Fixing bleed and adjusting levels in post-production is 10x easier when channels aren't baked together. 🎙️🎚️",
    tags: ["podcastproduction", "audioengineering", "workflow", "sound"],
    likes: 310,
    comments: 25,
    reposts: 62,
    views: 5100,
    hoursAgo: 100,
  },
  {
    userId: "user_elenarostova",
    content: "The hypnotic warmth of an analog bucket brigade delay (BBD) pedal. As repeats decay, high frequencies roll off into dark, velvety echoes. Perfect for ambient pads. 📼✨",
    tags: ["effects", "guitartech", "synth", "ambient"],
    likes: 290,
    comments: 22,
    reposts: 51,
    views: 4600,
    hoursAgo: 102,
  },
  {
    userId: "user_alexrivers",
    content: "Good UI design gets out of the way. Great UI design makes the underlying human communication feel effortlessly intimate and joyful. 🎨❤️",
    tags: ["uidesign", "productphilosophy", "ux", "craft"],
    likes: 480,
    comments: 41,
    reposts: 97,
    views: 7800,
    hoursAgo: 104,
  },
  {
    userId: "user_maya_patel",
    content: "Streaming LLM token responses over Server-Sent Events (SSE) provides immediate perceptual responsiveness for users compared to blocking HTTP requests. Latency perception is everything. ⚡🤖",
    tags: ["sse", "streaming", "ai", "fullstack"],
    likes: 540,
    comments: 46,
    reposts: 112,
    views: 8600,
    hoursAgo: 106,
  },
  {
    userId: "user_sophiaz",
    content: "CSS Grid vs Flexbox: Flexbox for one-dimensional linear groupings (navbars, pill rows, button clusters); CSS Grid for two-dimensional structural page layouts and responsive bento cards. 📐💻",
    tags: ["css", "frontend", "grid", "flexbox"],
    likes: 510,
    comments: 43,
    reposts: 124,
    views: 8200,
    hoursAgo: 108,
  },
  {
    userId: "user_marcuschen",
    content: "Implementing QUIC and HTTP/3 connection migration. When your phone switches from home Wi-Fi to cellular 5G, audio streams continue without dropping a single packet. Magic of modern networking. 📡⚡",
    tags: ["quic", "http3", "networking", "mobile"],
    likes: 470,
    comments: 38,
    reposts: 95,
    views: 7400,
    hoursAgo: 110,
  },
  {
    userId: "user_amara_okafor",
    content: "When building fintech onboarding: keep KYC simple, explain why documents are required, and give instant verification status. Friction at the gateway kills conversion. 💳✨",
    tags: ["fintech", "kyc", "ux", "productstrategy"],
    likes: 430,
    comments: 31,
    reposts: 82,
    views: 6900,
    hoursAgo: 112,
  },
  {
    userId: "user_davidk",
    content: "Morning fog over the Han River in Seoul. The subtle blue hour palette before the sun pierces through the mist is pure cinematic poetry. 📷🌊",
    media: "https://images.unsplash.com/photo-1517154421773-0529f29ea451?auto=format&fit=crop&w=1200&q=80",
    tags: ["seoul", "korea", "bluehour", "photography"],
    likes: 620,
    comments: 45,
    reposts: 108,
    views: 9800,
    hoursAgo: 114,
  },
  {
    userId: "user_liam_o_connor",
    content: "The superpower of small teams: we can ship an entire user-requested feature in 48 hours while enterprise committees are still scheduling their quarterly kickoff meetings. Stay nimble. ⚡🚀",
    tags: ["startups", "indiehackers", "speed", "shipping"],
    likes: 540,
    comments: 48,
    reposts: 116,
    views: 8700,
    hoursAgo: 116,
  },
  {
    userId: "user_kenji_sato",
    content: "Custom particle emitter generating swirling aurora borealis ribbons on WebGL. Modulating color gradients with audio pitch frequencies creates a mesmerizing visual symphony. 🌌✨",
    media: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    tags: ["aurora", "webgl", "particles", "generativeart"],
    likes: 410,
    comments: 33,
    reposts: 86,
    views: 6600,
    hoursAgo: 118,
  },
  {
    userId: "user_zara_alvarez",
    content: "Accessible audio player UX: provide large scrubbing sliders, clear time remaining counters, keyboard shortcuts (Space for Play/Pause, M for Mute), and visible closed captions. 🎧♿",
    tags: ["a11y", "audioplayer", "ux", "accessibility"],
    likes: 380,
    comments: 29,
    reposts: 78,
    views: 6100,
    hoursAgo: 120,
  },
  {
    userId: "user_clara_valdez",
    content: "Geometric shadow play on white stucco walls in Andalusia. Simplicity is not the absence of clutter; it is the presence of intention. ☀️📐",
    media: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    tags: ["spain", "minimalism", "shadows", "photography"],
    likes: 310,
    comments: 22,
    reposts: 49,
    views: 4800,
    hoursAgo: 122,
  },
  {
    userId: "user_devon_miles",
    content: "Using dynamic EQ to tame harsh vocal sibilance (6-8 kHz) only when it occurs, rather than applying a static notch filter that dulls the overall vocal presence. Smart mixing is surgical! 🎚️🎙️",
    tags: ["audioengineering", "mixing", "vocals", "dynamiceq"],
    likes: 350,
    comments: 27,
    reposts: 71,
    views: 5600,
    hoursAgo: 124,
  },
  {
    userId: "user_elenarostova",
    content: "Composing generative soundscapes with microtonal scales. Escaping standard 12-tone equal temperament opens up an entirely new emotional universe. 🎹🌌",
    tags: ["microtonal", "sounddesign", "ambient", "musictheory"],
    likes: 270,
    comments: 24,
    reposts: 48,
    views: 4300,
    hoursAgo: 126,
  },
  {
    userId: "user_alexrivers",
    content: "The importance of empty space in UI: negative space gives human eyes room to breathe, establishes hierarchy, and guides focus without needing loud borders or harsh colors. 🎨✨",
    tags: ["uidesign", "whitespace", "visualhierarchy", "craft"],
    likes: 450,
    comments: 36,
    reposts: 92,
    views: 7300,
    hoursAgo: 128,
  },
  {
    userId: "user_maya_patel",
    content: "Automated podcast transcript summarization using semantic clustering. Generating chapter markers, key takeaways, and searchable quotes in under 2 seconds. The future is here. 🤖🎙️",
    tags: ["ai", "podcasts", "transcription", "nlp"],
    likes: 520,
    comments: 42,
    reposts: 106,
    views: 8300,
    hoursAgo: 130,
  },
  {
    userId: "user_sophiaz",
    content: "Fluid typography with CSS `clamp(1rem, 2.5vw + 0.5rem, 2.5rem)` scales perfectly across every viewport without clunky breakpoint jumps. Pure mathematical elegance. 📐💻",
    tags: ["css", "fluidtypography", "frontend", "responsive"],
    likes: 490,
    comments: 39,
    reposts: 115,
    views: 7900,
    hoursAgo: 132,
  },
  {
    userId: "user_marcuschen",
    content: "Monitoring audio jitter buffers across distributed client sessions using eBPF probes on Linux edge nodes. Instant visibility into packet drops before users even notice glitching. ⚡🔍",
    tags: ["ebpf", "linux", "monitoring", "audio"],
    likes: 410,
    comments: 31,
    reposts: 84,
    views: 6500,
    hoursAgo: 134,
  },
  {
    userId: "user_amara_okafor",
    content: "Direct creator subscriptions and recurring monthly tips empower writers, audio hosts, and artists to plan long-term work without depending on volatile algorithmic ads. 🌟💸",
    tags: ["creatoreconomy", "subscriptions", "monetization", "independence"],
    likes: 580,
    comments: 49,
    reposts: 122,
    views: 9200,
    hoursAgo: 136,
  },
  {
    userId: "user_davidk",
    content: "Reflections of old brick warehouses in Amsterdam canals on an autumn evening. Golden leaves floating on dark green water. 🍂🛶",
    media: "https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?auto=format&fit=crop&w=1200&q=80",
    tags: ["amsterdam", "autumn", "travel", "photography"],
    likes: 640,
    comments: 47,
    reposts: 115,
    views: 10100,
    hoursAgo: 138,
  },
  {
    userId: "user_liam_o_connor",
    content: "Build what people actually search for, solve an annoying recurring problem, and price it fairly. You don't need venture capital to build a deeply profitable life. 🚀☕",
    tags: ["bootstrapping", "saas", "indiehackers", "freedom"],
    likes: 510,
    comments: 43,
    reposts: 109,
    views: 8200,
    hoursAgo: 140,
  },
  {
    userId: "user_kenji_sato",
    content: "Interactive 3D sound sphere where audio tracks map to floating glowing orbs in space. Dragging orbs closer to your virtual avatar increases spatial volume and reverb realism. 🎧🌐",
    media: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=1200&q=80",
    tags: ["threejs", "spatialaudio", "webgl", "interactive"],
    likes: 430,
    comments: 36,
    reposts: 91,
    views: 6900,
    hoursAgo: 142,
  },
  {
    userId: "user_zara_alvarez",
    content: "Remember to label all interactive icon-only buttons with descriptive `aria-label` tags. A button containing just an icon without a label is completely invisible to screen reader users. ♿🏷️",
    tags: ["a11y", "accessibility", "html", "webdev"],
    likes: 390,
    comments: 28,
    reposts: 84,
    views: 6300,
    hoursAgo: 144,
  },
  {
    userId: "user_clara_valdez",
    content: "Raw stone archway in an ancient Greek monastery on Mount Athos. The way stone absorbs morning warmth and radiates calm silence is breathtaking. 🏛️☀️",
    media: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
    tags: ["greece", "architecture", "history", "photography"],
    likes: 330,
    comments: 21,
    reposts: 47,
    views: 5100,
    hoursAgo: 146,
  },
  {
    userId: "user_devon_miles",
    content: "Always check your audio mix in mono before finishing. If your stereo widening tricks cause phase cancellation, your podcast will sound hollow on smartphone speakers and mono bluetooth units. 📻🔊",
    tags: ["soundengineering", "mono", "phasecancellation", "audiomixing"],
    likes: 360,
    comments: 29,
    reposts: 74,
    views: 5800,
    hoursAgo: 148,
  },
  {
    userId: "user_spacesnext",
    content: "Welcome to our 100+ active creator discussions on Spaces! Explore trending topics, tune in to live audio stages, tip your favorite creators, and connect with creative minds worldwide. ✨🚀",
    media: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    tags: ["spaces", "community", "creators", "welcome"],
    likes: 920,
    comments: 88,
    reposts: 230,
    views: 16000,
    hoursAgo: 150,
  },
];

const RAW_POST_TEMPLATES = [
  ...BASE_RAW_POST_TEMPLATES,
  ...SEED_POSTS_BATCH_1,
  ...SEED_POSTS_BATCH_2,
  ...SEED_POSTS_EXTRA_200,
  ...SEED_POSTS_BATCH_3_100,
];

export const SEED_POSTS: Post[] = RAW_POST_TEMPLATES.map((item, idx) => ({
  id: `post_seed_${idx + 1}`,
  user_id: item.userId,
  content: item.content,
  media_url: item.media ?? null,
  tags: item.tags,
  poll: item.poll ?? null,
  created_at: new Date(Date.now() - item.hoursAgo * 3600 * 1000).toISOString(),
  likeCount: item.likes,
  commentCount: item.comments,
  repostCount: item.reposts,
  viewCount: item.views,
  liked: false,
  bookmarked: false,
  reposted: false,
}));

/* ----------------------------------------------------------------- Comments */

export const SEED_COMMENTS: Record<string, PostComment[]> = {
  post_seed_1: [
    {
      id: "comm_1_1",
      post_id: "post_seed_1",
      user_id: "user_alexrivers",
      content: "The low-end saturation on those tape loops sounded immaculate in the live room!",
      created_at: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    },
    {
      id: "comm_1_2",
      post_id: "post_seed_1",
      user_id: "user_marcuschen",
      content: "Which audio interface did you use for the spatial monitoring?",
      created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    },
  ],
  post_seed_2: [
    {
      id: "comm_2_1",
      post_id: "post_seed_2",
      user_id: "user_sophiaz",
      content: "Sub-50ms audio latency is game-changing. It makes multi-speaker banter feel truly natural.",
      created_at: new Date(Date.now() - 100 * 60 * 1000).toISOString(),
    },
  ],
  post_seed_5: [
    {
      id: "comm_5_1",
      post_id: "post_seed_5",
      user_id: "user_liam_o_connor",
      content: "Paystack support makes international and mobile money creator payouts seamless! Huge milestone.",
      created_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    },
  ],
};

/* ----------------------------------------------------------------- Stories */

export const SEED_STORIES: Story[] = [
  {
    id: "story_seed_1",
    user_id: "user_elenarostova",
    media_url: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=800&q=80",
    image_url: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=800&q=80",
    type: "image",
    caption: "Soundcheck for tonight's ambient room 🎛️",
    view_count: 140,
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 22 * 3600 * 1000).toISOString(),
  },
  {
    id: "story_seed_2",
    user_id: "user_alexrivers",
    media_url: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80",
    image_url: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80",
    type: "image",
    caption: "Refining the new design token tokens ✨",
    view_count: 215,
    created_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 20 * 3600 * 1000).toISOString(),
  },
  {
    id: "story_seed_3",
    user_id: "user_davidk",
    media_url: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80",
    image_url: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80",
    type: "image",
    caption: "Shinjuku at twilight 📷",
    view_count: 320,
    created_at: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 18 * 3600 * 1000).toISOString(),
  },
  {
    id: "story_seed_4",
    user_id: "user_maya_patel",
    media_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    image_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    type: "image",
    caption: "AI model benchmarks running on device 🤖⚡",
    view_count: 480,
    created_at: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 16 * 3600 * 1000).toISOString(),
  },
  {
    id: "story_seed_5",
    user_id: "user_amara_okafor",
    media_url: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&q=80",
    image_url: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&q=80",
    type: "image",
    caption: "Paystack instant withdrawal testing complete! 💸✨",
    view_count: 510,
    created_at: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 14 * 3600 * 1000).toISOString(),
  },
];

/* ----------------------------------------------------------------- Spaces */

export const SEED_SPACES: Space[] = [
  {
    id: "space_seed_1",
    title: "Late Night Ambient Session & Live Modular Synthesizers",
    host_id: "user_elenarostova",
    host_name: "Elena Rostova",
    topic: "Music & Sound",
    listeners: 142,
    live: true,
    is_live: true,
    gradient: "from-purple-600 via-pink-600 to-rose-600",
    recorded: true,
    participants: [
      { id: "user_elenarostova", role: "host", isMuted: false },
      { id: "user_alexrivers", role: "speaker", isMuted: true },
      { id: "user_marcuschen", role: "listener", isMuted: true },
      { id: "user_sophiaz", role: "listener", isMuted: true },
    ],
    messages: [
      { id: "sm_1", userId: "user_alexrivers", name: "Alex", body: "The sub bass reverb sounds incredible.", createdAt: new Date().toISOString() },
      { id: "sm_2", userId: "user_marcuschen", name: "Marcus", body: "Crystal clear audio stream, zero latency drops.", createdAt: new Date().toISOString() },
    ],
  },
  {
    id: "space_seed_2",
    title: "Future of Creator Monetization: Tips & Paystack Payouts",
    host_id: "user_spacesnext",
    host_name: "Spaces Next",
    topic: "Product & Creator Economy",
    listeners: 320,
    live: true,
    is_live: true,
    gradient: "from-emerald-600 via-teal-600 to-cyan-700",
    recorded: true,
    participants: [
      { id: "user_spacesnext", role: "host", isMuted: false },
      { id: "user_amara_okafor", role: "speaker", isMuted: false },
      { id: "user_sophiaz", role: "speaker", isMuted: false },
      { id: "user_liam_o_connor", role: "listener", isMuted: true },
    ],
    messages: [
      { id: "sm_3", userId: "user_sophiaz", name: "Sophia", body: "Direct tip integration makes supporting creators seamless.", createdAt: new Date().toISOString() },
      { id: "sm_4", userId: "user_amara_okafor", name: "Amara", body: "Paystack mobile money rails are working super smoothly across Africa!", createdAt: new Date().toISOString() },
    ],
  },
  {
    id: "space_seed_3",
    title: "Spatial UI & Typography for Next-Gen Displays",
    host_id: "user_alexrivers",
    host_name: "Alex Rivers",
    topic: "Design & UX",
    listeners: 84,
    live: false,
    is_live: false,
    gradient: "from-blue-600 via-indigo-600 to-violet-700",
    recorded: true,
    participants: [
      { id: "user_alexrivers", role: "host", isMuted: true },
      { id: "user_sophiaz", role: "speaker", isMuted: true },
    ],
    messages: [],
  },
  {
    id: "space_seed_4",
    title: "Indie SaaS Playbook: From Zero to $20k MRR",
    host_id: "user_liam_o_connor",
    host_name: "Liam O'Connor",
    topic: "Startups & Indie Hacking",
    listeners: 195,
    live: false,
    is_live: false,
    gradient: "from-amber-600 via-orange-600 to-red-700",
    recorded: true,
    participants: [
      { id: "user_liam_o_connor", role: "host", isMuted: true },
    ],
    messages: [],
  },
];

/* ----------------------------------------------------------------- Conversations */

export const SEED_CONVERSATIONS: Conversation[] = [
  {
    id: "conv_elena",
    participant_id: "user_elenarostova",
    preview: "Loved your feedback on the ambient mix! The bass frequencies sounded pristine.",
    unread: 0,
    online: true,
    updated_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
  },
  {
    id: "conv_alex",
    participant_id: "user_alexrivers",
    preview: "Sent over the prototype Figma file with the updated glass panel components.",
    unread: 1,
    online: true,
    updated_at: new Date(Date.now() - 48 * 60 * 1000).toISOString(),
  },
  {
    id: "conv_marcus",
    participant_id: "user_marcuschen",
    preview: "Audio latency test passed at 38ms! Ready to co-host tomorrow's space.",
    unread: 0,
    online: false,
    updated_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
  },
  {
    id: "conv_amara",
    participant_id: "user_amara_okafor",
    preview: "The Paystack mobile payout worked immediately. Thanks for setting it up!",
    unread: 0,
    online: true,
    updated_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
  },
];

export const SEED_MESSAGES: Record<string, Message[]> = {
  conv_elena: [
    {
      id: "msg_elena_1",
      conversation_id: "conv_elena",
      sender_id: "user_elenarostova",
      body: "Hey! Did you manage to catch the end of our live room earlier?",
      created_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    },
    {
      id: "msg_elena_2",
      conversation_id: "conv_elena",
      sender_id: "guest",
      body: "Yes! The ambient transition into the tape loop was mind-blowing.",
      created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    },
    {
      id: "msg_elena_3",
      conversation_id: "conv_elena",
      sender_id: "user_elenarostova",
      body: "Loved your feedback on the ambient mix! The bass frequencies sounded pristine.",
      created_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    },
  ],
  conv_alex: [
    {
      id: "msg_alex_1",
      conversation_id: "conv_alex",
      sender_id: "user_alexrivers",
      body: "Sent over the prototype Figma file with the updated glass panel components.",
      created_at: new Date(Date.now() - 48 * 60 * 1000).toISOString(),
    },
  ],
  conv_marcus: [
    {
      id: "msg_marcus_1",
      conversation_id: "conv_marcus",
      sender_id: "user_marcuschen",
      body: "Audio latency test passed at 38ms! Ready to co-host tomorrow's space.",
      created_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    },
  ],
  conv_amara: [
    {
      id: "msg_amara_1",
      conversation_id: "conv_amara",
      sender_id: "user_amara_okafor",
      body: "The Paystack mobile payout worked immediately. Thanks for setting it up!",
      created_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    },
  ],
};

/* ----------------------------------------------------------------- Notifications */

export const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: "notif_1",
    type: "tip",
    actor_id: "user_alexrivers",
    body: "sent you a $25.00 creator tip via Paystack! 'Amazing content, keep it up!'",
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    read: false,
  },
  {
    id: "notif_2",
    type: "like",
    actor_id: "user_elenarostova",
    body: "liked your post",
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    read: true,
  },
  {
    id: "notif_3",
    type: "space",
    actor_id: "user_marcuschen",
    body: "invited you to speak in 'Late Night Ambient Session'",
    created_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    read: true,
  },
  {
    id: "notif_4",
    type: "tip",
    actor_id: "user_amara_okafor",
    body: "sent you a $50.00 creator tip via Paystack! 'Incredible audio space presentation!'",
    created_at: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    read: true,
  },
];
