export interface SeedPostTemplate {
  userId: string;
  content: string;
  media?: string | null;
  tags: string[];
  poll?: {
    id: string;
    question: string;
    options: { id: string; text: string; votes: number }[];
    totalVotes: number;
  };
  likes: number;
  comments: number;
  reposts: number;
  views: number;
  hoursAgo: number;
}

export const SEED_POSTS_BATCH_1: SeedPostTemplate[] = [
  // 1. Tech Humor & Dev Life
  {
    userId: "user_kai_turing",
    content: "Nothing unites a team of 40 senior engineers faster than someone accidentally deleting the dev database 4 minutes before sprint demo. We are suddenly agile, collaborative, and deeply spiritual. 💀🔥",
    tags: ["techhumor", "devlife", "engineering", "startups"],
    likes: 842,
    comments: 93,
    reposts: 215,
    views: 12400,
    hoursAgo: 1,
  },
  {
    userId: "user_kai_turing",
    content: "My code when I write it: ✨ Shakespearean elegance ✨\n\nMy code 6 months later: 'Who let an enraged raccoon with a keyboard commit directly to main?'",
    tags: ["programming", "humor", "codereview"],
    likes: 1205,
    comments: 140,
    reposts: 310,
    views: 18900,
    hoursAgo: 3,
  },
  {
    userId: "user_hannah_brooks",
    content: "Corporate Translation Guide:\n- 'Per my last email' = Did you even read it?\n- 'Let’s take this offline' = Stop embarrassing us in front of the VP.\n- 'Circling back' = I will haunt you until you answer.\n- 'Exciting challenge' = We have 0 budget and 3 days. 🫠",
    media: "https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?auto=format&fit=crop&w=1200&q=80",
    tags: ["corporatehumor", "remotework", "culture", "startuplife"],
    likes: 1890,
    comments: 245,
    reposts: 580,
    views: 29000,
    hoursAgo: 4,
  },
  {
    userId: "user_kai_turing",
    content: "Interactive Dev Poll: What is the single most terrifying moment in modern software engineering?",
    tags: ["developer", "humor", "poll", "devops"],
    poll: {
      id: "poll_dev_fear",
      question: "What induces instant cold sweats?",
      options: [
        { id: "opt_1", text: "git push origin main --force", votes: 890 },
        { id: "opt_2", text: "AWS Bill notification at 2:00 AM", votes: 1240 },
        { id: "opt_3", text: "'Hey do you have 5 mins?' from CEO", votes: 760 },
        { id: "opt_4", text: "Merge conflict in 4,000-line lockfile", votes: 615 },
      ],
      totalVotes: 3505,
    },
    likes: 640,
    comments: 88,
    reposts: 95,
    views: 8900,
    hoursAgo: 5,
  },
  {
    userId: "user_hannah_brooks",
    content: "A product manager, an engineer, and a designer walk into a bar. The engineer orders a beer. Orders 0 beers. Orders 9999999 beers. Orders a lizard. The designer asks for the foam to be OKLCH #fafafa. The PM asks if the bar can scale to 10M concurrent drinkers by Q3. 🍻",
    tags: ["humor", "tech", "productmanagement", "ux"],
    likes: 1420,
    comments: 112,
    reposts: 340,
    views: 19400,
    hoursAgo: 6,
  },

  // 2. Specialty Coffee & Culinary Science
  {
    userId: "user_priya_sharma",
    content: "Brewing an anaerobic natural Gesha from Huila, Colombia this morning. 93°C water, 1:16 ratio on a flat-bottom dripper. Tasting notes of bergamot, candied peach, and jasmine. Coffee isn't just caffeine—it's organic chemistry in a ceramic cup. ☕✨",
    media: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=80",
    tags: ["specialtycoffee", "pourover", "coffeeroaster", "sensory"],
    likes: 410,
    comments: 48,
    reposts: 52,
    views: 5200,
    hoursAgo: 2,
  },
  {
    userId: "user_priya_sharma",
    content: "Specialty Coffee Poll: If you could only keep ONE brew method for the rest of your life, which one stays on the counter?",
    tags: ["coffee", "barista", "poll", "lifestyle"],
    poll: {
      id: "poll_coffee_methods",
      question: "Which coffee brewer reigns supreme?",
      options: [
        { id: "opt_1", text: "V60 / Kalita Wave Pour Over", votes: 940 },
        { id: "opt_2", text: "AeroPress (Inverted only!)", votes: 720 },
        { id: "opt_3", text: "Double-shot Espresso Machine", votes: 1150 },
        { id: "opt_4", text: "French Press / Cold Brew", votes: 310 },
      ],
      totalVotes: 3120,
    },
    likes: 380,
    comments: 79,
    reposts: 41,
    views: 6100,
    hoursAgo: 7,
  },
  {
    userId: "user_priya_sharma",
    content: "The water you use accounts for 98.5% of your brew. If your tap water has high bicarbonate levels, it completely mutes delicate floral acidity. Test your PPM and mineral balance before spending $40 on micro-lot beans! 💧☕",
    media: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
    tags: ["coffeelover", "baristalife", "extraction", "chemistry"],
    likes: 295,
    comments: 31,
    reposts: 38,
    views: 4300,
    hoursAgo: 10,
  },

  // 3. Indie Gaming & Cyberpunk Game Dev
  {
    userId: "user_samir_k",
    content: "Added volumetric neon rain shaders to our cyberpunk detective RPG. When you step under streetlights in the low-light district, the CRT reflections on wet asphalt react dynamically to your health meter. 🎮🌧️💜",
    media: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80",
    tags: ["gamedev", "indiegame", "pixelart", "cyberpunk", "shaders"],
    likes: 910,
    comments: 84,
    reposts: 190,
    views: 14200,
    hoursAgo: 3,
  },
  {
    userId: "user_samir_k",
    content: "Game Dev Question: What made older PS1 / SNES soundtracks stick in our heads for 25 years? Strict voice polyphony limits forced composers to write indelible, unforgettable melodies instead of relying on cinematic wall-of-sound orchestration. 🎹👾",
    tags: ["gamemusic", "chiptune", "soundtrack", "gamedesign"],
    likes: 580,
    comments: 63,
    reposts: 112,
    views: 8700,
    hoursAgo: 8,
  },

  // 4. Fitness, Ultra Endurance & Longevity
  {
    userId: "user_chloe_dubois",
    content: "24km sunrise trail run through the alpine ridge. 1,400m elevation gain. Kept heart rate locked strictly in Zone 2 (132-138 bpm). Consistency beats heroic burnouts every single week. 🏔️🏃‍♀️",
    media: "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?auto=format&fit=crop&w=1200&q=80",
    tags: ["trailrunning", "ultraendurance", "fitness", "zone2", "mountains"],
    likes: 720,
    comments: 54,
    reposts: 68,
    views: 9400,
    hoursAgo: 4,
  },
  {
    userId: "user_chloe_dubois",
    content: "Fitness Community Poll: What is your #1 non-negotiable recovery protocol after high-intensity training?",
    tags: ["recovery", "biohacking", "fitness", "wellness"],
    poll: {
      id: "poll_recovery",
      question: "Your top recovery weapon?",
      options: [
        { id: "opt_1", text: "8.5+ hours uninterrupted sleep", votes: 1420 },
        { id: "opt_2", text: "Infrared Sauna & Cold Plunge", votes: 610 },
        { id: "opt_3", text: "Targeted hydration + electrolytes", votes: 530 },
        { id: "opt_4", text: "Active recovery walk / light spin", votes: 340 },
      ],
      totalVotes: 2900,
    },
    likes: 490,
    comments: 42,
    reposts: 35,
    views: 7100,
    hoursAgo: 9,
  },

  // 5. Astrophysics, Space & Cosmic Philosophy
  {
    userId: "user_dr_tariq_amin",
    content: "New JWST spectroscopy data just detected complex polycyclic aromatic hydrocarbons in a galaxy that formed only 950 million years after the Big Bang. The building blocks of organic chemistry formed much earlier in cosmic history than previously thought. 🌌🔭",
    media: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    tags: ["astronomy", "jwst", "cosmology", "physics", "science"],
    likes: 1650,
    comments: 132,
    reposts: 420,
    views: 24500,
    hoursAgo: 6,
  },
  {
    userId: "user_dr_tariq_amin",
    content: "When you look at the stars tonight, remember: every carbon atom in your DNA, every calcium atom in your bones, and every iron atom in your blood was forged inside the fiery heart of a collapsing star billions of years ago. We are literally the cosmos knowing itself. ✨",
    tags: ["philosophy", "universe", "stargazing", "deepthoughts"],
    likes: 2100,
    comments: 180,
    reposts: 640,
    views: 31000,
    hoursAgo: 11,
  },

  // 6. African Tech & Innovation Hubs
  {
    userId: "user_amara_okafor",
    content: "Nairobi's Silicon Savannah and Lagos' Yaba tech corridor are showing the world how to leapfrog legacy banking. Mobile money penetration and instant Paystack rails have created entire economies of digital creators who get paid globally in seconds. 🌍🚀",
    media: "https://images.unsplash.com/photo-1577962917302-cd874c4e31d2?auto=format&fit=crop&w=1200&q=80",
    tags: ["africatech", "fintech", "paystack", "innovation", "creatoreconomy"],
    likes: 890,
    comments: 95,
    reposts: 210,
    views: 13400,
    hoursAgo: 5,
  },
  {
    userId: "user_amara_okafor",
    content: "Community Poll: For creators based in emerging markets, what is the biggest barrier to scaling revenue internationally?",
    tags: ["creators", "fintech", "globalcommerce", "poll"],
    poll: {
      id: "poll_creator_barriers",
      question: "Biggest barrier for global creator revenue?",
      options: [
        { id: "opt_1", text: "Cross-border payout fees & FX spreads", votes: 1120 },
        { id: "opt_2", text: "Payment processor geoblocking", votes: 940 },
        { id: "opt_3", text: "Audience discovery & reach", votes: 680 },
        { id: "opt_4", text: "Complex tax and compliance rules", votes: 410 },
      ],
      totalVotes: 3150,
    },
    likes: 540,
    comments: 67,
    reposts: 88,
    views: 8200,
    hoursAgo: 12,
  },

  // 7. Generative AI & Autonomous Agents
  {
    userId: "user_maya_patel",
    content: "Local LLMs running in browser via WebGPU with quantized FP4 weights just hit 42 tokens/sec on an M3 Max laptop. Zero cloud API calls, 100% private user data, offline-first. This changes personal AI tools forever. 🧠⚡",
    media: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=1200&q=80",
    tags: ["localai", "webgpu", "machinelearning", "privacy", "futuretech"],
    likes: 1120,
    comments: 104,
    reposts: 310,
    views: 17800,
    hoursAgo: 4,
  },
  {
    userId: "user_maya_patel",
    content: "AI Poll: Will software engineers in 2030 be writing raw code, or orchestrating swarms of verifiable AI agents?",
    tags: ["artificialintelligence", "futureofwork", "poll", "software"],
    poll: {
      id: "poll_ai_future",
      question: "How will software be built in 2030?",
      options: [
        { id: "opt_1", text: "Orchestrating AI agent swarms", votes: 1340 },
        { id: "opt_2", text: "Hybrid (AI drafts, humans verify)", votes: 1680 },
        { id: "opt_3", text: "Handcrafted code remains dominant", votes: 420 },
      ],
      totalVotes: 3440,
    },
    likes: 670,
    comments: 92,
    reposts: 84,
    views: 10400,
    hoursAgo: 13,
  },

  // 8. Architecture & Brutalist Minimal Design
  {
    userId: "user_clara_valdez",
    content: "Board-formed concrete, geometric skylights, and dramatic shadows in Kyoto's modern archives. Architecture is the art of giving physical form to silence. 🏛️📐",
    media: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
    tags: ["architecture", "minimalism", "concrete", "photography", "design"],
    likes: 820,
    comments: 46,
    reposts: 115,
    views: 11200,
    hoursAgo: 7,
  },
  {
    userId: "user_clara_valdez",
    content: "Design Rule: If a space feels chaotic, don't buy more storage. Remove 30% of the objects and let the remaining negative space breathe. Luxury is quietness. 🌿",
    tags: ["interiordesign", "minimalist", "spaces", "lifestyle"],
    likes: 950,
    comments: 61,
    reposts: 140,
    views: 13800,
    hoursAgo: 14,
  },

  // 9. Sound Engineering & Modular Synths
  {
    userId: "user_elenarostova",
    content: "Patching a Buchla 259 dual oscillator through an analog spring reverb tank. The warmth of harmonic distortion at the edge of saturation is something digital plugins can only emulate. Analog circuitry has a soul. 🎛️🔊",
    media: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&q=80",
    tags: ["modularsynth", "sounddesign", "buchla", "analog", "musicproduction"],
    likes: 670,
    comments: 52,
    reposts: 89,
    views: 9100,
    hoursAgo: 8,
  },
  {
    userId: "user_devon_miles",
    content: "Pro Audio Tip: Stop boosting 10kHz to get 'clarity' in your podcasts. Instead, notch out the muddy resonance around 320Hz-450Hz. You'll instantly get broadcast-grade warmth without harsh sibilance. 🎙️🎚️",
    tags: ["podcasting", "mixing", "soundengineering", "audio"],
    likes: 540,
    comments: 38,
    reposts: 76,
    views: 7400,
    hoursAgo: 15,
  },

  // 10. Indie Hacking & SaaS Metrics
  {
    userId: "user_liam_o_connor",
    content: "Hit $18,400 MRR on our developer feedback widget today! 🚀\n- 0 VC funding\n- 1 full-time founder (me)\n- 1 part-time contractor\n- 82% gross margins\n\nProfitability gives you the freedom to build what customers actually love, without pitch decks or vanity metrics. 📈🛠️",
    media: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
    tags: ["indiehackers", "buildinpublic", "saas", "bootstrapping", "mrr"],
    likes: 1430,
    comments: 165,
    reposts: 280,
    views: 22000,
    hoursAgo: 6,
  },
  {
    userId: "user_liam_o_connor",
    content: "The best marketing hack in SaaS is simply answering support emails in 3 minutes with a personalized loom video. Customers will stay with you for 4 years and tell all their friends. Treat humans like humans. ❤️",
    tags: ["customerexperience", "growth", "startuptips"],
    likes: 890,
    comments: 72,
    reposts: 120,
    views: 12600,
    hoursAgo: 16,
  },

  // 11. Street Photography & Cinematography
  {
    userId: "user_davidk",
    content: "Midnight rain in Shinjuku, shot on Kodak Portra 400 with a 35mm f/1.4 lens. Film captures the glow of neon signs and shadows with a tactile grain that digital sensors still struggle to replicate. 📷🌃",
    media: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
    tags: ["streetphotography", "35mm", "filmphotography", "tokyo", "cinematography"],
    likes: 1350,
    comments: 98,
    reposts: 240,
    views: 19800,
    hoursAgo: 9,
  },
  {
    userId: "user_davidk",
    content: "Cinematography rule of thumb: Light the space, not just the actor. When the ambient environment has contrast and depth, your subject naturally pops off the screen. 🎬💡",
    tags: ["filmmaking", "lighting", "cinematography", "visualarts"],
    likes: 720,
    comments: 44,
    reposts: 95,
    views: 9800,
    hoursAgo: 17,
  },

  // 12. Design Systems & Accessibility
  {
    userId: "user_sophiaz",
    content: "Never disable the CSS focus ring `:focus-visible` without replacing it with an accessible, high-contrast alternative. Millions of keyboard users navigate the web every day. Empathy is good design. ♿✨",
    tags: ["accessibility", "a11y", "webdesign", "frontend", "ux"],
    likes: 980,
    comments: 63,
    reposts: 190,
    views: 14500,
    hoursAgo: 10,
  },
  {
    userId: "user_zara_alvarez",
    content: "Typography Tip: Set your line-height proportionally to your line length. For narrow mobile columns (35-45 characters), 1.4x line height is perfect. For wide reading columns (65-75 characters), increase line height to 1.65x to prevent eye fatigue. 📖✍️",
    tags: ["typography", "designsystems", "ui", "readability"],
    likes: 640,
    comments: 39,
    reposts: 88,
    views: 8900,
    hoursAgo: 18,
  },

  // 13. Distributed Systems & Performance
  {
    userId: "user_marcuschen",
    content: "Replacing JSON payloads with Protocol Buffers + gRPC across our internal audio metadata workers reduced network bandwidth by 73% and cut serialization CPU time by 4x. Binary formats are king for high-throughput live streams. ⚡💻",
    media: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80",
    tags: ["distributedsystems", "grpc", "backend", "performance", "golang"],
    likes: 810,
    comments: 71,
    reposts: 145,
    views: 11900,
    hoursAgo: 11,
  },
  {
    userId: "user_marcuschen",
    content: "There are two hard problems in computer science: cache invalidation, naming things, and off-by-one errors in distributed consensus algorithms. 😅",
    tags: ["computerscience", "humor", "backend", "concurrency"],
    likes: 1190,
    comments: 86,
    reposts: 260,
    views: 17200,
    hoursAgo: 19,
  },

  // 14. WebGL, Shaders & Creative Coding
  {
    userId: "user_kenji_sato",
    content: "Real-time raymarched fractal Julia set running in a single GLSL fragment shader at 120 FPS on mobile. Math is the most beautiful canvas we have. 🎨🧮",
    media: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
    tags: ["webgl", "glsl", "shaders", "creativecoding", "generativeart"],
    likes: 1240,
    comments: 88,
    reposts: 280,
    views: 18500,
    hoursAgo: 12,
  },
  {
    userId: "user_kenji_sato",
    content: "Creative Coding Poll: What is your preferred framework for real-time 3D browser experiences?",
    tags: ["threejs", "webgl", "webgpu", "poll"],
    poll: {
      id: "poll_3d_tools",
      question: "Top 3D Web Framework?",
      options: [
        { id: "opt_1", text: "Three.js / React Three Fiber", votes: 1410 },
        { id: "opt_2", text: "Raw WebGL / GLSL Shaders", votes: 430 },
        { id: "opt_3", text: "WebGPU / WGSL (The Future)", votes: 980 },
        { id: "opt_4", text: "Babylon.js", votes: 290 },
      ],
      totalVotes: 3110,
    },
    likes: 520,
    comments: 48,
    reposts: 64,
    views: 7900,
    hoursAgo: 20,
  },

  // 15. More Dev Humor & Everyday Work Stories
  {
    userId: "user_kai_turing",
    content: "Client: 'Can we build an AI-powered social network that runs on blockchain and uses quantum encryption by next Tuesday?'\n\nMe: 'Sure, would you like a unicorn with that or just the complimentary nervous breakdown?' 🦄",
    tags: ["freelance", "clients", "devhumor", "consulting"],
    likes: 1540,
    comments: 135,
    reposts: 390,
    views: 23400,
    hoursAgo: 13,
  },
  {
    userId: "user_hannah_brooks",
    content: "Status update: I have now spent 45 minutes formatting my Obsidian notes about how to be more productive instead of actually doing the work. Peak workflow optimization achieved. 📝✨",
    tags: ["productivity", "obsidian", "procrastination", "humor"],
    likes: 1320,
    comments: 110,
    reposts: 275,
    views: 19800,
    hoursAgo: 21,
  },

  // 16. Audio Spaces & Live Conversation Culture
  {
    userId: "user_alexrivers",
    content: "Live audio spaces have a unique intimacy that pre-recorded podcasts can't match. When someone stumbles over their words or laughs genuinely with co-hosts, the raw humanity breaks through the screen. Unfiltered conversation is sacred. 🎙️❤️",
    media: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1200&q=80",
    tags: ["liveaudio", "spaces", "community", "podcasting", "connection"],
    likes: 780,
    comments: 59,
    reposts: 110,
    views: 11400,
    hoursAgo: 14,
  },
  {
    userId: "user_spacesnext",
    content: "Spaces Tip of the Day: Use headphones when hosting or speaking in a live room! It enables crystal clear acoustic echo cancellation and lets your listeners hear every nuance of your voice without feedback loops. 🎧✨",
    tags: ["audio", "spaces", "creators", "protipps"],
    likes: 620,
    comments: 34,
    reposts: 88,
    views: 9500,
    hoursAgo: 22,
  },

  // 17. Sourdough & Fermentation Culinary Science
  {
    userId: "user_priya_sharma",
    content: "78% hydration country sourdough loaf fresh out of the cast iron Dutch oven. 24-hour cold fermentation in the fridge developed that deep blistered crust and open crumb. Flour, water, salt, wild yeast, and patience. 🥖🔥",
    media: "https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?auto=format&fit=crop&w=1200&q=80",
    tags: ["sourdough", "baking", "fermentation", "culinary", "slowfood"],
    likes: 910,
    comments: 72,
    reposts: 95,
    views: 13200,
    hoursAgo: 15,
  },
  {
    userId: "user_samir_k",
    content: "Why do indie developers love pixel art? It's not nostalgia—it's high semantic density. When every pixel must convey meaning, you eliminate visual noise and focus purely on gameplay readability. 🎨👾",
    tags: ["pixelart", "gamedesign", "indiedev", "artdirection"],
    likes: 740,
    comments: 51,
    reposts: 118,
    views: 10800,
    hoursAgo: 23,
  },

  // 18. Nature, Hiking & Digital Detox
  {
    userId: "user_chloe_dubois",
    content: "Turned off all phone notifications and spent 36 hours in the deep redwood forest with just a notebook, water filter, and tent. Your brain resets completely when the only sound is pine needles and wind. Unplug to recharge. 🌲⛺",
    media: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80",
    tags: ["digitaldetox", "nature", "mindfulness", "backpacking", "calm"],
    likes: 1250,
    comments: 89,
    reposts: 195,
    views: 18900,
    hoursAgo: 16,
  },
  {
    userId: "user_dr_tariq_amin",
    content: "The James Webb telescope mirror is 6.5 meters across and gold-coated to reflect infrared light with 98% efficiency. It allows us to observe galaxies that emitted their photons over 13.4 billion years ago. We are literally peering into the dawn of time. 🔭✨",
    tags: ["astronomy", "jwst", "physics", "deepspace", "exploration"],
    likes: 1480,
    comments: 94,
    reposts: 330,
    views: 22100,
    hoursAgo: 24,
  },

  // Additional 60 diverse posts completing Batch 1
  {
    userId: "user_kai_turing",
    content: "Frontend devs spending 6 hours deciding between 4px and 6px border-radius vs Backend devs returning raw SQL error messages with database passwords in the response body. 🤝 Balanced team dynamics.",
    tags: ["frontend", "backend", "humor", "webdev"],
    likes: 1680,
    comments: 142,
    reposts: 420,
    views: 25400,
    hoursAgo: 17,
  },
  {
    userId: "user_hannah_brooks",
    content: "My favorite tech interview question: 'Tell me about a time you made a mistake.'\n\n'Well, in 2021 I agreed to maintain a legacy Java codebase that uses XML configuration files from 2006.' Instant offer. 🤝😂",
    tags: ["interview", "techhumor", "recruiting", "career"],
    likes: 1390,
    comments: 98,
    reposts: 280,
    views: 21200,
    hoursAgo: 25,
  },
  {
    userId: "user_elenarostova",
    content: "Recorded the sound of morning rain hitting corrugated zinc roofs in Costa Rica with binaural microphones. When you drop these hydrophone textures under an analog Moog bassline, the whole track feels alive. 🌧️🎧",
    media: "https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?auto=format&fit=crop&w=1200&q=80",
    tags: ["fieldrecording", "binaural", "ambient", "sounddesign", "music"],
    likes: 640,
    comments: 41,
    reposts: 78,
    views: 8900,
    hoursAgo: 18,
  },
  {
    userId: "user_maya_patel",
    content: "Why open-source AI weights matter: True scientific progress relies on peer reproducibility. When research is walled inside black-box proprietary APIs, discovery slows down. Open source fuels the global creative frontier. 🌐🚀",
    tags: ["opensource", "ai", "research", "science", "innovation"],
    likes: 1040,
    comments: 87,
    reposts: 260,
    views: 16200,
    hoursAgo: 26,
  },
  {
    userId: "user_amara_okafor",
    content: "Our creator tipping leaderboard shows that fans love tipping during live discussions when their favorite hosts answer direct questions! Real-time gratitude via Paystack creates an instant feedback loop between creator and supporter. 💸✨",
    tags: ["monetization", "paystack", "creators", "community"],
    likes: 720,
    comments: 54,
    reposts: 105,
    views: 11200,
    hoursAgo: 19,
  },
  {
    userId: "user_liam_o_connor",
    content: "3 Things I stopped doing when building my software company:\n1. Reading tech crunch funding rounds\n2. Attending networking mixers without an agenda\n3. Redesigning my landing page every Sunday\n\nStarted talking to 5 paying customers every week instead. Game changer. 🎯",
    tags: ["startups", "indiehackers", "founder", "focus"],
    likes: 1180,
    comments: 94,
    reposts: 210,
    views: 18200,
    hoursAgo: 27,
  },
  {
    userId: "user_davidk",
    content: "Street portrait of a master ceramicist in Kyoto. Hands covered in wet clay, soft northern window light. Character and decades of mastery captured in a single 1/125s shutter click. 📷🍵",
    media: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1200&q=80",
    tags: ["portrait", "craftsmanship", "japan", "streetphotography"],
    likes: 930,
    comments: 58,
    reposts: 130,
    views: 13400,
    hoursAgo: 20,
  },
  {
    userId: "user_sophiaz",
    content: "OKLCH color space is a revolution for web designers because it provides perceptual uniformity. In sRGB, yellow at 80% lightness looks blinding while blue at 80% looks washed out. OKLCH fixes this mathematically. 🎨📐",
    tags: ["color", "oklch", "css", "designtheory", "webdesign"],
    likes: 850,
    comments: 62,
    reposts: 165,
    views: 13800,
    hoursAgo: 28,
  },
  {
    userId: "user_clara_valdez",
    content: "Cast concrete textures meeting raw warm oak wood. When architectural materials don't hide their origins, a room feels grounded and permanent. Minimalist living space study. 🏛️🪵",
    media: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    tags: ["interiordesign", "architecture", "minimalism", "aesthetic"],
    likes: 760,
    comments: 39,
    reposts: 92,
    views: 11100,
    hoursAgo: 21,
  },
  {
    userId: "user_priya_sharma",
    content: "The ritual of grinding fresh single-origin coffee beans every morning is my meditation before the screen lights up. What is your morning ritual that keeps you grounded?",
    tags: ["mindfulness", "morningroutine", "coffee", "lifestyle"],
    likes: 540,
    comments: 68,
    reposts: 42,
    views: 7900,
    hoursAgo: 29,
  },
  {
    userId: "user_samir_k",
    content: "Building an inventory system where items have tactile weight and physical sound when moved in your backpack. Sound design in user interfaces makes digital actions feel tangible. 🎒🔊",
    tags: ["gamedev", "sounddesign", "uiux", "interactivity"],
    likes: 670,
    comments: 45,
    reposts: 88,
    views: 9600,
    hoursAgo: 22,
  },
  {
    userId: "user_chloe_dubois",
    content: "Hydration isn't just drinking plain water. If you are sweating on long runs, you need sodium, potassium, and magnesium to maintain cellular osmosis. Prevent cramps before they start! ⚡💧",
    tags: ["running", "nutrition", "biohacking", "endurance"],
    likes: 490,
    comments: 36,
    reposts: 55,
    views: 7400,
    hoursAgo: 30,
  },
  {
    userId: "user_dr_tariq_amin",
    content: "Hubble vs James Webb: Hubble observes ultraviolet and optical wavelengths, while JWST penetrates cosmic dust clouds with deep infrared optics. Together, they give humanity eyes to see the invisible universe. 🌌🔭",
    media: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
    tags: ["astronomy", "jwst", "hubble", "space", "cosmology"],
    likes: 1390,
    comments: 88,
    reposts: 290,
    views: 20400,
    hoursAgo: 23,
  },
  {
    userId: "user_kai_turing",
    content: "Junior Dev: 'Why did you spend 3 hours writing a bash script for a 30-second task?'\n\nSenior Dev: 'Because now I can do that task automatically in 0.2 seconds for the next 7 years.' That's investment banking for geeks. 🧠💻",
    tags: ["automation", "bash", "linux", "devhumor"],
    likes: 1820,
    comments: 138,
    reposts: 480,
    views: 27900,
    hoursAgo: 31,
  },
  {
    userId: "user_hannah_brooks",
    content: "Shoutout to everyone who has ever nodded intently in a Zoom meeting while their brain was actually playing elevator music and wondering what to have for lunch. We see you. We are you. 🥗🎶",
    tags: ["remotework", "zoom", "humor", "workculture"],
    likes: 1640,
    comments: 124,
    reposts: 390,
    views: 24800,
    hoursAgo: 24,
  },
  {
    userId: "user_kenji_sato",
    content: "Fluid dynamics simulation in WebGL using Navier-Stokes grid approximations. When you drag your mouse across the canvas, dye particles disperse and swirl with turbulent curl noise. Pure visual satisfaction. 🌊💻",
    media: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1200&q=80",
    tags: ["fluidsimulation", "webgl", "glsl", "generativeart", "creativecoding"],
    likes: 1180,
    comments: 79,
    reposts: 240,
    views: 17300,
    hoursAgo: 25,
  },
  {
    userId: "user_marcuschen",
    content: "Designing an ultra-low latency WebRTC mesh network where participants automatically elect relay nodes based on ping topology. Sub-30ms audio sync between Tokyo, San Francisco, and London. ⚡🌐",
    tags: ["webrtc", "networking", "lowlatency", "audio", "systems"],
    likes: 740,
    comments: 52,
    reposts: 110,
    views: 10800,
    hoursAgo: 32,
  },
  {
    userId: "user_zara_alvarez",
    content: "Dark mode is not just inverted white mode! If you use pure #000000 black background with #ffffff pure white text, the extreme contrast causes halation and visual vibration for people with astigmatism. Use #121214 with #e2e8f0. ✨👁️",
    tags: ["darkmode", "a11y", "accessibility", "uiux", "design"],
    likes: 1290,
    comments: 98,
    reposts: 310,
    views: 19800,
    hoursAgo: 26,
  },
  {
    userId: "user_devon_miles",
    content: "The best mic in the world won't save a room with bare parallel drywall. Before spending $1,000 on a Shure SM7B, hang heavy wool blankets or acoustic rockwool panels. Treat your acoustic environment first! 🎙️🏠",
    tags: ["acoustics", "podcasting", "soundengineering", "homestudio"],
    likes: 680,
    comments: 48,
    reposts: 95,
    views: 9400,
    hoursAgo: 33,
  },
  {
    userId: "user_alexrivers",
    content: "Spatial audio in virtual spaces creates a sense of physical co-presence. When someone speaks from your upper-left and another chimes in from the right, your brain maps their locations instantly. Audio geometry matters. 🎧🌐",
    tags: ["spatialaudio", "spaces", "ui", "futuretech", "metaverse"],
    likes: 810,
    comments: 53,
    reposts: 120,
    views: 12100,
    hoursAgo: 27,
  },
];
