import type { SeedPostTemplate } from "./seed-posts-batch1";

export const SEED_POSTS_BATCH_2: SeedPostTemplate[] = [
  // 1. Tech Humor & Dev Relatability
  {
    userId: "user_kai_turing",
    content: "Day 48 of reading legacy documentation: 'Do not remove this commented-out line, the server crashes if it is deleted.' I tested it. The server indeed exploded. We worship the ghost line now. 🕯️👻",
    tags: ["legacycode", "devhumor", "programming", "bugs"],
    likes: 1980,
    comments: 182,
    reposts: 540,
    views: 31200,
    hoursAgo: 2,
  },
  {
    userId: "user_hannah_brooks",
    content: "Nothing prepares you for the emotional whiplash of fixing a production bug in 30 seconds only to realize you caused it in the previous commit 12 minutes ago. 🤡🎪",
    tags: ["devlife", "humor", "git", "startuplife"],
    likes: 1420,
    comments: 98,
    reposts: 310,
    views: 21900,
    hoursAgo: 5,
  },
  {
    userId: "user_kai_turing",
    content: "Why do programmers wear headphones? 10% music, 90% acoustic forcefield against unsolicited scope creep. 🎧🛡️",
    tags: ["humor", "developers", "headphones", "focus"],
    likes: 1750,
    comments: 110,
    reposts: 420,
    views: 26500,
    hoursAgo: 8,
  },
  {
    userId: "user_hannah_brooks",
    content: "Quick Startup Valuation Formula:\n- Revenue: $12k/yr\n- SaaS Tooling Stack: $45k/yr\n- Pitch deck with 6 uses of 'Synergistic AI Flywheel': $40M pre-money. 🦄✨",
    tags: ["venturecapital", "startups", "satire", "techhumor"],
    likes: 2150,
    comments: 195,
    reposts: 680,
    views: 38400,
    hoursAgo: 10,
  },

  // 2. Specialty Coffee & Artisanal Food
  {
    userId: "user_priya_sharma",
    content: "Dialing in an Ethiopian Yirgacheffe on the Mazzer grinder. 18.2g in, 42g liquid out in 27.5 seconds at 9 bar pressure. Tasting notes of bright Meyer lemon, honey blossom, and black tea finish. Espresso is precision fluid mechanics. ☕🍋",
    media: "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=1200&q=80",
    tags: ["espresso", "specialtycoffee", "baristalife", "yirgacheffe"],
    likes: 620,
    comments: 49,
    reposts: 64,
    views: 8400,
    hoursAgo: 3,
  },
  {
    userId: "user_priya_sharma",
    content: "Culinary Poll: Sourdough baking hydration preference for artisanal loaves?",
    tags: ["baking", "sourdough", "culinary", "poll"],
    poll: {
      id: "poll_baking_hydration",
      question: "Your ideal sourdough dough hydration?",
      options: [
        { id: "opt_1", text: "70% - 74% (Easy shaping, solid crumb)", votes: 640 },
        { id: "opt_2", text: "75% - 80% (Sweet spot open crumb)", votes: 1420 },
        { id: "opt_3", text: "80%+ (High risk, maximum blistered pockets)", votes: 890 },
      ],
      totalVotes: 2950,
    },
    likes: 480,
    comments: 52,
    reposts: 41,
    views: 7100,
    hoursAgo: 12,
  },

  // 3. Game Dev & Cyberpunk Worlds
  {
    userId: "user_samir_k",
    content: "Crafting procedural rain ripples on neon puddle reflections using compute shaders. When player footsteps disrupt the water surface, caustics warp in real-time under street lamp lights. 🌧️🎮💜",
    media: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80",
    tags: ["gamedev", "shaders", "pixelart", "indiegames", "cyberpunk"],
    likes: 1120,
    comments: 76,
    reposts: 210,
    views: 16500,
    hoursAgo: 4,
  },
  {
    userId: "user_samir_k",
    content: "Indie Game Insight: The best game feel comes from the 'coyote time' jump window (allowing jumps 80ms after walking off a ledge) and jump buffering (registering a jump 100ms before landing). Player psychology > strict physics. 🕹️✨",
    tags: ["gamefeel", "gamedesign", "indiedev", "physics"],
    likes: 890,
    comments: 63,
    reposts: 175,
    views: 13200,
    hoursAgo: 14,
  },

  // 4. Fitness, Ultra Running & Biohacking
  {
    userId: "user_chloe_dubois",
    content: "Early morning interval track session: 6x 1,000m at 3:20/km pace with 90s active recovery jogs. Mental fortitude is forged in the last 200 meters of the final repeat. Stay relentless. 🏃‍♀️🔥",
    media: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=1200&q=80",
    tags: ["trackandfield", "running", "intervals", "endurance", "fitness"],
    likes: 840,
    comments: 62,
    reposts: 78,
    views: 11400,
    hoursAgo: 6,
  },
  {
    userId: "user_chloe_dubois",
    content: "Cold Plunge Poll: How cold do you set your recovery water immersion?",
    tags: ["coldplunge", "biohacking", "wellness", "poll"],
    poll: {
      id: "poll_cold_temp",
      question: "Your favorite cold plunge temperature?",
      options: [
        { id: "opt_1", text: "3°C - 5°C (37°F - 41°F) Arctic Ice", votes: 890 },
        { id: "opt_2", text: "6°C - 10°C (42°F - 50°F) Crisp Recovery", votes: 1240 },
        { id: "opt_3", text: "11°C - 15°C (51°F - 59°F) Gentle Cooling", votes: 410 },
      ],
      totalVotes: 2540,
    },
    likes: 410,
    comments: 38,
    reposts: 31,
    views: 6200,
    hoursAgo: 16,
  },

  // 5. Deep Space & Astrophysics
  {
    userId: "user_dr_tariq_amin",
    content: "Gravitational lensing: When a massive galaxy cluster bends space-time, it acts as a cosmic magnifying glass, allowing us to see faint dwarf galaxies located directly behind it. Einstein's general relativity predicted this over 100 years ago. 🌌🔬",
    media: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=1200&q=80",
    tags: ["gravitationallensing", "astronomy", "einstein", "physics", "universe"],
    likes: 1840,
    comments: 142,
    reposts: 490,
    views: 27800,
    hoursAgo: 7,
  },
  {
    userId: "user_dr_tariq_amin",
    content: "If the entire 13.8 billion year history of the universe were compressed into a single calendar year, all of human recorded history would take place in the final 14 seconds before midnight on December 31st. Perspective is everything. ⏳✨",
    tags: ["cosmology", "carlsagan", "history", "perspective", "philosophy"],
    likes: 2490,
    comments: 210,
    reposts: 780,
    views: 39500,
    hoursAgo: 18,
  },

  // 6. African Fintech & Global Creator Economy
  {
    userId: "user_amara_okafor",
    content: "Paystack direct creator payouts just settled into Kenyan M-PESA wallets in under 2 seconds! This level of financial interoperability across African currencies is opening up immense global revenue for audio hosts, podcasters, and digital writers. 🌍💸",
    media: "https://images.unsplash.com/photo-1556742049-0a67e557224f?auto=format&fit=crop&w=1200&q=80",
    tags: ["fintech", "paystack", "mpesa", "africa", "monetization"],
    likes: 1140,
    comments: 108,
    reposts: 280,
    views: 17200,
    hoursAgo: 8,
  },
  {
    userId: "user_amara_okafor",
    content: "Direct creator tipping transforms the relationship between hosts and listeners. When you tip a creator directly via Paystack, 100% of the appreciation is personal, transparent, and immediate. The era of middlemen taking 50% cuts is fading. 🚀✨",
    tags: ["creatoreconomy", "tips", "monetization", "empowerment"],
    likes: 890,
    comments: 74,
    reposts: 160,
    views: 13900,
    hoursAgo: 20,
  },

  // 7. Generative AI & Autonomous Software
  {
    userId: "user_maya_patel",
    content: "Multi-modal model benchmarks for spatial audio transcription just achieved 99.1% speaker separation in crowded rooms with 8 overlapping voices. Clean audio rooms with instant AI summaries are now production ready. 🤖🎧",
    media: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80",
    tags: ["artificialintelligence", "multimodal", "audioai", "speech", "research"],
    likes: 1280,
    comments: 96,
    reposts: 340,
    views: 19800,
    hoursAgo: 9,
  },
  {
    userId: "user_maya_patel",
    content: "Building with small, fine-tuned 3B parameter models running directly on device is vastly faster, cheaper, and more reliable for specific workflows than repeatedly calling monolithic 500B cloud endpoints. Small is nimble. ⚡🧠",
    tags: ["edgeml", "ai", "efficiency", "softwareengineering"],
    likes: 980,
    comments: 84,
    reposts: 240,
    views: 15400,
    hoursAgo: 22,
  },

  // 8. Architecture, Minimal Interiors & Woodcraft
  {
    userId: "user_clara_valdez",
    content: "A Japanese tea pavilion built with interlocking cedar joints (tsugite) without a single nail or metal screw. Wood expands and contracts with the seasons, making the structure self-healing over centuries. Timeless craft. 🍵🪵",
    media: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
    tags: ["woodworking", "japan", "architecture", "craftsmanship", "timber"],
    likes: 1420,
    comments: 87,
    reposts: 310,
    views: 20800,
    hoursAgo: 11,
  },
  {
    userId: "user_clara_valdez",
    content: "Light is the fourth dimension of architecture. The way winter morning shadows sweep across raw plaster walls completely changes how time feels inside a home. ☀️🏛️",
    tags: ["architecture", "lighting", "minimalism", "spatial"],
    likes: 850,
    comments: 48,
    reposts: 120,
    views: 12400,
    hoursAgo: 24,
  },

  // 9. Analog Soundscapes & Vinyl Mastering
  {
    userId: "user_elenarostova",
    content: "Mastering an ambient EP to 180g heavy vinyl. Cutting the lacquer disc requires careful phase alignment in the low frequencies (below 150Hz) to prevent the cutting stylus from jumping out of the groove. Physical audio physics is magical. 🎵🎛️",
    media: "https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=1200&q=80",
    tags: ["vinyl", "mastering", "audiophile", "musicproduction", "ambient"],
    likes: 940,
    comments: 67,
    reposts: 155,
    views: 14200,
    hoursAgo: 13,
  },
  {
    userId: "user_devon_miles",
    content: "Voice Recording Checklist for Spaces Hosts:\n1. Dynamic cardioid mic 3-4 inches from mouth\n2. Gain staged to peak at -12dBFS\n3. Gentle high-pass filter at 80Hz\n4. Closed-back monitoring headphones\n\nYour listeners will thank you! 🎙️🎧",
    tags: ["audiotips", "podcasting", "spaces", "homestudio"],
    likes: 710,
    comments: 42,
    reposts: 110,
    views: 10400,
    hoursAgo: 25,
  },

  // 10. Indie Hacking & Building in Public
  {
    userId: "user_liam_o_connor",
    content: "Customer retention > Customer acquisition. We spent the last month fixing 40 tiny UI papercuts reported by power users instead of launching new features. Monthly churn dropped from 4.2% to 1.6%. Polish pays compound interest. 📈✨",
    media: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80",
    tags: ["buildinpublic", "saas", "indiehackers", "retention", "metrics"],
    likes: 1290,
    comments: 115,
    reposts: 260,
    views: 19500,
    hoursAgo: 15,
  },
  {
    userId: "user_liam_o_connor",
    content: "Pricing Experiment: We replaced our complicated 5-tier pricing grid with 2 crystal-clear plans ($7/mo Plus and $23/mo Pro) with annual discounts. Conversion rate jumped 38% overnight. Simplicity converts. 💳🚀",
    tags: ["pricing", "growth", "startuptips", "conversion"],
    likes: 980,
    comments: 82,
    reposts: 190,
    views: 14900,
    hoursAgo: 27,
  },

  // 11. Street Photography & Cinematic Color Grading
  {
    userId: "user_davidk",
    content: "Dawn fog over Seoul's Han River bridges. Shot with a circular polarizing filter on a 50mm prime to cut surface reflections and isolate the geometric steel trusses in the mist. 📷🌉",
    media: "https://images.unsplash.com/photo-1517154421773-0529f29ea451?auto=format&fit=crop&w=1200&q=80",
    tags: ["photography", "seoul", "fog", "cinematography", "prime50mm"],
    likes: 1190,
    comments: 74,
    reposts: 210,
    views: 17800,
    hoursAgo: 17,
  },
  {
    userId: "user_davidk",
    content: "Why shoot prime lenses instead of zooms? Constraining yourself to a single focal length forces you to move your body, discover unique angles, and master spatial perspective. Constraints fuel creativity. 📸",
    tags: ["photography", "cameratips", "visualart", "creativity"],
    likes: 820,
    comments: 54,
    reposts: 125,
    views: 11800,
    hoursAgo: 28,
  },

  // 12. Design Systems & Micro-Interactions
  {
    userId: "user_sophiaz",
    content: "Spring animations feel 10x more natural than easing curves because physical objects in the real world have mass, stiffness, and damping. Use spring physics for modal dismissals and drag gestures! 🎨✨",
    tags: ["animation", "microinteractions", "ui", "uxdesign", "framer"],
    likes: 1050,
    comments: 72,
    reposts: 230,
    views: 16100,
    hoursAgo: 19,
  },
  {
    userId: "user_zara_alvarez",
    content: "Every interactive button must have a clear visual active/pressed state (`active:scale-[0.98]`). Immediate tactile tactile feedback reassures users that their click registered before the server responds. 🔘⚡",
    tags: ["uiux", "userexperience", "designsystems", "frontend"],
    likes: 760,
    comments: 48,
    reposts: 98,
    views: 10900,
    hoursAgo: 30,
  },

  // 13. Distributed High-Performance Systems
  {
    userId: "user_marcuschen",
    content: "Zero-copy ring buffers in C++ and Rust for audio packet routing. Bypassing kernel memory copies shaved 14ms off our total roundtrip latency across live audio stages. Every microsecond counts in real-time conversations. ⚡🦀",
    media: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80",
    tags: ["rustlang", "systemsengineering", "lowlatency", "concurrency", "performance"],
    likes: 940,
    comments: 86,
    reposts: 195,
    views: 14700,
    hoursAgo: 21,
  },
  {
    userId: "user_kenji_sato",
    content: "Simulating volumetric clouds and atmospheric Rayleigh scattering in WebGL with raymarching step functions. Watching sunset colors shift dynamically based on sun angle elevation is hypnotic. ☁️🌅💻",
    media: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80",
    tags: ["webgl", "raymarching", "shaders", "creativecoding", "sunset"],
    likes: 1340,
    comments: 92,
    reposts: 290,
    views: 20500,
    hoursAgo: 23,
  },

  // 14. Philosophical Thoughts & Book Summaries
  {
    userId: "user_alexrivers",
    content: "Marcus Aurelius Meditations reminder: 'You have power over your mind - not outside events. Realize this, and you will find strength.' Essential reading for everyone navigating fast-moving tech cycles. 📖🏛️",
    tags: ["stoicism", "books", "philosophy", "mindset", "calm"],
    likes: 1580,
    comments: 112,
    reposts: 380,
    views: 24200,
    hoursAgo: 26,
  },
  {
    userId: "user_spacesnext",
    content: "Welcome to our 300+ vibrant creator community posts across design, WebGL, AI, comedy, specialty coffee, audio production, and African tech innovation! Connect, tip your favorite creators, join live audio rooms, and share your craft. 🌟🚀",
    tags: ["community", "spaces", "creators", "welcome", "monetization"],
    likes: 2100,
    comments: 180,
    reposts: 640,
    views: 35000,
    hoursAgo: 1,
  },
];
